### ISSUE TITLE
Default link color is slightly different from Magnetic

### ISSUE THREAD

**Issue by vdineva** [cisco-sbg-ui/magna-react#105]
in the[ Magnetic specs ]( https://www.figma.com/file/oVZWatImEIbl1c8sjdGxi0/%F0%9F%A7%B2--Magnetic-Design-Library?node-id=5171%3A45637&t=S1cr8PK078be9eWP-0) the color for a link is `#326CD1` and the default we get from Magna-react is `#306acf`

![Screenshot 2023-01-19 at 10 59 11](https://user-images.githubusercontent.com/791418/213491232-884109ce-0ab6-4ee7-a849-3866670a83bc.png)
![Screenshot 2023-01-19 at 10 58 53](https://user-images.githubusercontent.com/791418/213491240-66462fa6-eee1-4121-bb84-7b18ce33d835.png)

**Comment by rwharrisjr** [comment]
I think that may be an old design file with the old color token scheme. The one we've been basing magna-react on is https://www.figma.com/file/oVZWatImEIbl1c8sjdGxi0/branch/yU3qYkj6T2kfN4XYtUkEeD/%F0%9F%A7%B2--Magnetic-Design-Library?node-id=33305%3A351801&t=SZVIEaaPHO09PowY-0

**Comment by vdineva** [comment]
I think you're right - closing this issue
