### ISSUE TITLE
Labels for form inputs should use font-weight: 600

### ISSUE THREAD

**Issue by keweeks** [cisco-sbg-ui/magna-react#112]
**Screenshots**

![Screenshot 2023-01-23 at 9 29 58 AM](https://user-images.githubusercontent.com/33638380/214108387-324f38ad-bc10-4bad-af45-945e675cafc6.png)

![Screenshot 2023-01-23 at 9 30 29 AM](https://user-images.githubusercontent.com/33638380/214108511-be186cf7-90e3-44a5-ae57-50049cd66bfc.png)

**Comment by rwharrisjr** [comment]
Resolved in #115
