### ISSUE TITLE
ATextInput is rendered narrower in Firefox when disabled

### ISSUE THREAD

**Issue by MikkCZ** [cisco-sbg-ui/magna-react#117]
**Describe the bug**
In Firefox, when the `ATextInput` is rendered with `disabled={true}`, it's narrower compared to the case when the prop's value is `false`. This makes the layout jump when the prop changes during loading of data.

**To Reproduce**
1. Have `<ATextInput ... disabled={true} />` in the page.
2. Load the page in Firefox.
3. Measure the input's width.
4. Change the `disabled` value to `false`.
5. Measure again - the widths are different.

**Expected behavior**
The width of both inputs is the same. Which is the case in Chrome.

**Screenshots**
![obrazek](https://user-images.githubusercontent.com/3941344/214266420-12fd439b-fc10-401e-9c92-62cf63b39086.png)

**Environment (please complete the following information):**
 - Device: MacBook
 - OS: Venture 13.1
 - Browser Firefox
 - Version 110.0b3

**Additional context**
The issue is not reproducible for me, when there are two inputs right next to each other inside the same `<APanelHeader>`. But when I add an extra `<APanelHeader>` and put the second input there, it is reproducible again.

Also in Firefox the total width of the input is greater than in Chrome, which may or may not be related.

**Comment by rwharrisjr** [comment]
@MikkCZ Could you provide sample code that reproduces the issue?
