### ISSUE TITLE
ATextInput prependIcon does not support magnetic icons

### ISSUE THREAD

**Issue by keweeks** [cisco-sbg-ui/magna-react#119]
**Describe the bug**
Using an icon name from the magna set (ex: "magnifyingGlass") does not work with ATextInput.

**Expected behavior**
It should be possible to use icons from the magna set anywhere icons are rendered. It would be ideal to avoid an extra prop on ATextInput. Maybe the AIcon component could handle a fallback to iconSet="magna" if the icon is not found

**Comment by rwharrisjr** [comment]
This should be resolved by #141 when it gets merged.

**Comment by rwharrisjr** [comment]
All icons listed on https://magna-react.vercel.app/components/icon can now be used without an `iconSet` as expected.

Note that icons are now kebab-case to keep consistent with the base phosphor icons, so `magnifying-glass` can be used for `prependIcon` in this case.
