### ISSUE TITLE
Allow the user to set dimensions/size for the `AEmptyState` component

### ISSUE THREAD

**Issue by vdineva** [cisco-sbg-ui/magna-react#128]
I'm adding the `<AEmptyState />` component and it seems disproportionately big to rest of the elements on the page: 
![Screenshot 2023-01-25 at 13 58 48](https://user-images.githubusercontent.com/791418/214658419-326e88ee-4ca6-4992-9a93-a1a52ce76b52.png)

I tried passing in inline styles but with no success so far. It would be great if the width/height of this component can be easily adjusted

**Comment by rwharrisjr** [comment]
Resolved in #129
