### ISSUE TITLE
Wrong error icon for text field validation 

### ISSUE THREAD

**Issue by vdineva** [cisco-sbg-ui/magna-react#130]
The error icon for a text field with validation should probably be switched to  
![Screenshot 2023-01-27 at 14 40 36](https://user-images.githubusercontent.com/791418/215182266-f8d8b9bd-e6d4-47ae-9549-dd158074def6.png)

![Screenshot 2023-01-27 at 14 38 00](https://user-images.githubusercontent.com/791418/215182070-048941e2-497b-4b2d-8106-acf904a1bcea.png)

reference: https://www.figma.com/file/yU3qYkj6T2kfN4XYtUkEeD/Dark-Mode-%5BWiP%5D?node-id=4801%3A42872&t=zhkB76YkN2snX3aT-4

**Comment by rwharrisjr** [comment]
Will resolve after https://github.com/cisco-sbg-ui/magna-react/pull/141

**Comment by rwharrisjr** [comment]
Resolved
