### ISSUE TITLE
`usePopupQuickExit` closes `ADrawer` mistakenly when using `AMenu` to Open

### ISSUE THREAD

**Issue by radesai21** [cisco-sbg-ui/magna-react#143]
**Describe the bug**
`ADrawer` does not open when using an option in an `AMenu` to open the drawer mixed with `usePopupQuickExit` usage.

The `usePopupQuickExit`'s `onExit` callback is getting triggered to immediately close the drawer when trying to open. See the steps below to reproduce on the magna-react docs page.

Ultimately its `useOutsideClick` causing `onExit` to be called.

**To Reproduce**
1. Go to https://magna-react.vercel.app/components/drawer
2. Paste the following code snip into the first code editor block in the Drawer docs page:

```jsx
() => {
  const button3Ref = useRef(null);
  const [open3, setOpen3] = useState(false);

  const nonModalContentRef = useRef();
  const [nonModalOpen, setNonModalOpen] = useState(false);
  usePopupQuickExit({
    popupRef: nonModalContentRef,
    isEnabled: nonModalOpen,
    onExit: () => { setNonModalOpen(false); console.log('CLOSING DRAWER'); }
  });

  return (
    <>
      <p>Non-Modal Drawer Opened with a Menu Option</p>
      <AButton ref={button3Ref} onClick={() => setOpen3(true)}>Open Menu</AButton>
      <AMenu
        anchorRef={button3Ref}
        open={open3}
        placement="bottom-left"
        onClose={() => setOpen3(false)}
        style={{borderRadius: 0}}>
        <AListItem onClick={() => setNonModalOpen(true)}>Open Drawer</AListItem>
      </AMenu>
      <ADrawer
        ref={nonModalContentRef}
        asModal={false}
        isOpen={nonModalOpen}
        slideIn="right"
      >
          Hello World
      </ADrawer>
    </>
  );
};
```
3. Click the Button to Open the Menu
4. In the Menu use the Option to open the Drawer
5. Notice that the Drawer does not open
6. Check console & see log showing `onExit` was called when trying to open the Drawer

**Expected behavior**
The Drawer should be able to open and stay open with a dropdown menu. The drawer's `usePopupQuickExit` should not depend on the element used to open the drawer to be in the DOM.

**Screenshots**

https://user-images.githubusercontent.com/95231401/215842468-38d2344a-228f-4f38-b228-0f679bab6486.mov

**Environment (please complete the following information):**
 - Device: Desktop
 - OS: `MacOS`
 - Browser `Chrome, Safari, FF`
 - Version: `1.0.0-beta.13`

**Additional context**

This seems to happen when the element that is clicked on to open the drawer is removed from the DOM.

**Comment by brennarvo** [comment]
Hey @radesai21, thanks for such a thorough description of the issue.

The quickest fix for now (until I find a more bulletproof solution) is to add an `onTransitionEnd` handler to `ADrawer` in order to determine when it is fully opened. That way, the "Open Menu" button's click won't clash with the `click` event listener inside of `useOutsideClick`. Here's an example that you can paste into the playground in Magna React documentation:

```javascript
() => {
  const menuTriggerRef = useRef(null);
  const [isMenuOpen, setIsMenuOpen] = useState(false);

  const drawerContentRef = useRef();
  const [isDrawerOpen, setIsDrawerOpen] = useState(false);
  const [isAnimationFinished, setIsAnimationFinished] = useState(false);
  usePopupQuickExit({
    popupRef: drawerContentRef,
    isEnabled: isDrawerOpen && isAnimationFinished,
    onExit: () => {
      setIsDrawerOpen(false);
    },
  });

  return (
    <>
      <AButton ref={menuTriggerRef} onClick={() => setIsMenuOpen(true)}>
        Open Menu
      </AButton>
      <AMenu
        anchorRef={menuTriggerRef}
        open={isMenuOpen}
        placement="bottom-left"
        onClose={() => setIsMenuOpen(false)}
        style={{ borderRadius: 0 }}
      >
        <AListItem onClick={() => {
          setIsAnimationFinished(false)
          setIsDrawerOpen(true);
        }}>Open Drawer</AListItem>
      </AMenu>
      <ADrawer
        onTransitionEnd={() => setIsAnimationFinished(true)}
        ref={drawerContentRef}
        asModal={false}
        isOpen={isDrawerOpen}
        slideIn="right"
      >
        Hello World
      </ADrawer>
    </>
  );
};
```

Again, this isn't ideal, but should unblock you for the time being. Please let me know if you still have issues with this fix, and I'll be happy to assist.

In the meantime, I'll investigate further and come up with a solution baked into Magna React so that we don't have this problem in the future.

**Comment by radesai21** [comment]
Thanks for the quick workaround! It helped keep the drawer open. 

I came across some other behavior related to the `useOutsideClick` listener. When clicking on a button inside the drawer the drawer's `onExit` handler is getting called. 

I was able to reproduce it again in the MagnaReact playground:
```jsx
() => {
  const menuTriggerRef = useRef(null);
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const [someState, setSomeState] = useState(true);
  const drawerContentRef = useRef();
  const [isDrawerOpen, setIsDrawerOpen] = useState(false);
  const [isAnimationFinished, setIsAnimationFinished] = useState(false);
  usePopupQuickExit({
    popupRef: drawerContentRef,
    isEnabled: isDrawerOpen && isAnimationFinished,
    onExit: () => {
      setIsDrawerOpen(false);
    },
  });

  return (
    <>
      {someState.toString()}
      <AButton ref={menuTriggerRef} onClick={() => setIsMenuOpen(true)}>
        Open Menu
      </AButton>
      <AMenu
        anchorRef={menuTriggerRef}
        open={isMenuOpen}
        placement="bottom-left"
        onClose={() => setIsMenuOpen(false)}
        style={{ borderRadius: 0 }}
      >
        <AListItem onClick={() => {
          setIsAnimationFinished(false)
          setIsDrawerOpen(true);
        }}>Open Drawer</AListItem>
      </AMenu>
      <ADrawer
        onTransitionEnd={() => setIsAnimationFinished(true)}
        ref={drawerContentRef}
        asModal={false}
        isOpen={isDrawerOpen}
        slideIn="right"
      >
        Hello World
        { someState && (<AButton onClick={() => setSomeState(!someState)}>Some Action that should not close the drawer</AButton>) }
      </ADrawer>
    </>
  );
};
```

I think whats causing it to get triggered is that the `e.target`/button that was clicked is being removed from the DOM. So the `useOutsideClick` listener is triggering the `onExit` callback.
