### ISSUE TITLE
Button height is not per Magnetic specs

### ISSUE THREAD

**Issue by vdineva** [cisco-sbg-ui/magna-react#144]
**In Magnetic the height of a button is 34px:**
![Screenshot 2023-02-01 at 9 25 00](https://user-images.githubusercontent.com/791418/216069628-47da5da8-a786-4904-8c6e-17ee2b1a1a9b.png)

**and in Magna-react it's 28px:**
![Screenshot 2023-02-01 at 9 25 36](https://user-images.githubusercontent.com/791418/216069622-a2f14afa-5cfd-4dd9-bcc9-862ed1ad2460.png)

**Comment by rwharrisjr** [comment]
This is intentional as to not break existing uses of Button when migrating from atomic-react to magna-react. The AButton component has a `medium` property to increase the size to default magnetic where needed.
