### ISSUE TITLE
AButtonGroup should support medium prop

### ISSUE THREAD

**Issue by keweeks** [cisco-sbg-ui/magna-react#155]
Looking at: https://magna-react.vercel.app/components/button-group I notice that there is no support for the medium prop like buttons allow. 

It seems like this should be supported to maintain a consistent height with buttons/button groups

**Comment by rwharrisjr** [comment]
This can be accomplished now by adding `medium` to each button. Added an example to the button group page.

<img width="1130" alt="Screenshot 2023-02-07 at 4 23 20 PM" src="https://user-images.githubusercontent.com/23561587/217380481-091a9252-3554-4344-9f56-bbcd8816ceaa.png">


--- 
https://github.com/cisco-sbg-ui/magna-react/pull/156 Adds a `medium` prop to `AButtonGroup` for a less verbose syntax.

**Comment by keweeks** [comment]
🤦‍♂️
