### ISSUE TITLE
Color for AEmptyState message seems to be incorrect

### ISSUE THREAD

**Issue by keweeks** [cisco-sbg-ui/magna-react#160]
From https://www.figma.com/file/oVZWatImEIbl1c8sjdGxi0/%F0%9F%A7%B2--Magnetic-Design-Library?node-id=15437%3A56920&t=RXVvIOiI48krtVan-0 it seems like the color for default theme should be neutral-12 bt it looks like it grabs 

https://github.com/cisco-sbg-ui/magna-react/blob/1ca03acb1c6cacc94ab36b1e4936dea4ead729d3/framework/components/AEmptyState/AEmptyState.scss#L60

I don't know of a spec for dark theme but it seems like something like neutral-5 could work.

**Comment by rwharrisjr** [comment]
Updated light and dark colors in #161 

Fwiw, I've been basing dark theme off this version of the figma file as it has dark theme versions of components https://www.figma.com/file/oVZWatImEIbl1c8sjdGxi0/branch/yU3qYkj6T2kfN4XYtUkEeD/%F0%9F%A7%B2--Magnetic-Design-Library?node-id=33305%3A356756&t=FyPmPbl5VMh2QIxn-0. The figmas are still being edited though, so I expect we'll continue to see inconsistencies for a while.
