### ISSUE TITLE
Inline notifications for Input validationState

### ISSUE THREAD

**Issue by mvelkCisco** [cisco-sbg-ui/magna-react#170]
**Is your feature request related to a problem? Please describe.**

When implementing a form validation messages, I've been using `AInput` with a `validationState` and `hint` props to render validation errors. The result looked like this:
<img width="372" alt="image" src="https://user-images.githubusercontent.com/51229231/218695090-b04ac75f-7907-4163-9d3a-28a0063584d1.png">

After consulting with UX I was pointed to https://magnetic.cisco.com/0a43ab5cd/p/65f3dd-input-field/t/189dae. The validation message should apparently look like an inline notification:
<img width="370" alt="image" src="https://user-images.githubusercontent.com/51229231/218695232-6bb2c97f-d22a-4bc9-b528-d3b29745b045.png">

**Describe the solution you'd like**
I think input "hint" and input "validation message" should be 2 different features.

The hint text should still look like this:
<img width="328" alt="image" src="https://user-images.githubusercontent.com/51229231/218696195-6d44d15a-504f-4dfc-9fa5-17ff005c3d39.png">
Reference: https://magnetic.cisco.com/0a43ab5cd/p/65f3dd-input-field/t/77a108

And it probably should not be affected by `validationState`. Eg. for a hint like this I would not expect it to go red when there's a validation error:
<img width="364" alt="image" src="https://user-images.githubusercontent.com/51229231/218697145-2074fa19-7f3f-4889-adab-2516334913be.png">
But a confirmation with UX might be needed. 
The error notification could go below it.

For the validation message that renders as a notification, there could be a new prop, eg `validationMessage` (to match `validationState`), that could accept a react component and render `AAlert` with an appropriate `level` (and the provided component as a child).

**Comment by rwharrisjr** [comment]
Adding a `validationMessage` prop would necessitate change for implementations already using `hint` as the error message.

To maintain compatibility hint will now appear:
- as plaintext if there is no validation state
- inside an `AAlert` with the associated validation state

**Comment by AlexGoDe** [comment]
@mvelkCisco to answer your question on hints and validation error.  The hint itself should not go red, but the field itself + the inline validation error. Snapshot for reference
<img width="946" alt="Screenshot 2023-02-17 at 11 49 01 AM" src="https://user-images.githubusercontent.com/118300940/219758519-f58c6831-4c6d-4eb8-afd8-855fcd8c5405.png">
