### ISSUE TITLE
Update table headers to use correct hover/focus styling

### ISSUE THREAD

**Issue by sabrinamokerji** [cisco-sbg-ui/magna-react#182]
We noticed that the blue line added to the table headers in the recent magna upgrade looked odd when it was on wide columns. Additionally, since it's also on the focus state, the line would stay on a column after clicking and then appear on the next column when hovering, creating 1 giant line. 

I asked Yiping from the Magnetic team how this should behave and she informed me that the blue line is not used anywhere in the products and that the Figma is outdated. 

She said the correct styling is to add a light blue background color to interactive headers on hover only. The mouse should also be a pointer.

Screenshots from our convo:

<img width="1421" alt="Screenshot 2023-02-16 at 5 51 47 PM" src="https://user-images.githubusercontent.com/12389266/219514950-1e78cdcf-ff7a-40cb-88b7-e216a5c0e2ea.png">

<img width="1087" alt="Screenshot 2023-02-16 at 5 51 29 PM" src="https://user-images.githubusercontent.com/12389266/219514934-fb530598-6ee0-45c2-8b0b-a3fe6e30f5b4.png">

![image](https://user-images.githubusercontent.com/12389266/219515009-e52de53a-fc5a-4c15-9905-986f4b03cf20.png)

**Comment by sabrinamokerji** [comment]
Also wanted to add that the sort icon should not be all the way to the end of the table header like in her mock-up. I clarified this afterward. The way we have the icon next to the text is correct.

<img width="1420" alt="Screenshot 2023-02-16 at 9 49 46 PM" src="https://user-images.githubusercontent.com/12389266/219545020-53d48891-e8c2-4522-8dbc-f978983a0538.png">

Just the hover state needs to be changed and the focus state removed

**Comment by rwharrisjr** [comment]
To retain accessibility, focus state will not be removed
