### ISSUE TITLE
Add support for a custom display template in ASelect input

### ISSUE THREAD

**Issue by mvelkCisco** [cisco-sbg-ui/magna-react#183]
**Is your feature request related to a problem? Please describe.**

Currently `ASelect` seems to be only able to render either a placeholder, or a value from `items`. 
Reference: https://github.com/cisco-sbg-ui/magna-react/blob/canary/framework/components/ASelect/ASelect.js#L333

I'm implementing a custom select using `ASelect` that supports infinite loading of data on scroll. It basically makes an API call for the next page when the scrolling reaches a skeleton appended to the end of `items`.

Video preview: https://user-images.githubusercontent.com/51229231/219660607-4bfce65a-fa62-44b8-8ae4-aa26edf3b757.mov

Code reference (`AsyncSelect`): https://github.com/advthreat/intelligence/pull/67/files#diff-6f78b0603173c76b71b4403406099fe4e014e2f1f0ccb917d6381a09af49da18

The issue is that user can select a value that's not on the first page of the loaded data. Next time the page loads, the `items` don't contain the selected value, so it won't get displayed as selected (just the placeholder renders).

**Describe the solution you'd like**

A prop on `ASelect` that would allow setting a custom templating function similar to `itemTemplate`, but for the content of the select input. This would allow not only setting a custom display value (even not included in `items`), but also rich formatting like this:
<img width="378" alt="image" src="https://user-images.githubusercontent.com/51229231/219659749-520ec206-cfc3-4ef4-be51-a28b64dd188b.png">

Or at least a custom string value would be nice.

**Describe alternatives you've considered**

I figured out I can include the selected items that were not loaded to the `items` and then hide it using `css` in the `itemTemplate`.

See `hiddenSelectedItemsNotInLoadedItems`: https://github.com/advthreat/intelligence/pull/67/files#diff-6f78b0603173c76b71b4403406099fe4e014e2f1f0ccb917d6381a09af49da18R126

Template hiding: https://github.com/advthreat/intelligence/pull/67/files#diff-6f78b0603173c76b71b4403406099fe4e014e2f1f0ccb917d6381a09af49da18R78 

It seems to work, but it's super hacky.

**Comment by rwharrisjr** [comment]
Added three new props that I think should cover this scenario

![Screenshot 2023-02-21 at 9 36 45 AM](https://user-images.githubusercontent.com/23561587/220390378-a7fcd135-39c9-41df-ae94-a2cd7ec7bf4e.png)


`selectdDisplayTemplate` and `selectedDisplayItem` can be used together to display a custom component for an item that is not selected and does not have to be in the data set.
