### ISSUE TITLE
Incorrect spacing between buttons in APagniation component

### ISSUE THREAD

**Issue by rrubas** [cisco-sbg-ui/magna-react#198]
**Describe the bug**

<img width="189" alt="Screenshot 2023-02-27 at 11 45 55" src="https://user-images.githubusercontent.com/19386887/221543466-94243642-c6fc-41ed-8cd1-1fa69fb725e0.png">

**To Reproduce**
https://magna-react.vercel.app/components/pagination#install

**Expected behavior**
https://www.figma.com/file/oVZWatImEIbl1c8sjdGxi0/branch/yU3qYkj6T2kfN4XYtUkEeD/%F0%9F%A7%B2--Magnetic-Design-Library?node-id=5247%3A39676&t=gz5MsqKmULlimqSt-1
<img width="875" alt="Screenshot 2023-02-27 at 11 49 56" src="https://user-images.githubusercontent.com/19386887/221544410-f0943819-c036-45cb-9b2e-979ea482a707.png">

**Environment (please complete the following information):**
 - Device: Desktop
 - OS: Mac OS
 - Browser Chrome, Safari
 - Version latest

**Comment by mvelkCisco** [comment]
Please do not implement a fix for this. This is our first attempt to contribute directly but it looks like we don't have a write access. Added #199.
