### ISSUE TITLE
Requesting write access for Cognitive team + extend the team

### ISSUE THREAD

**Issue by mvelkCisco** [cisco-sbg-ui/magna-react#199]
Congnitive team would like to start contributing to magna-react repo but it looks like we only have a read access and can't push a branch, only make a fork.

The team: https://github.com/orgs/cisco-sbg-ui/teams/cognitive/repositories
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/51229231/221551152-2bdebb6f-76e0-4054-95e2-04ab0f1f6dde.png">

Also please add to the team: `rrubas` and `bredy` to the team.

cc @jkrupick.

**Comment by rwharrisjr** [comment]
Updated permission from Read to Write and sent invitations to join the team to the ids listed.

**Comment by mvelkCisco** [comment]
Thanks!
