### ISSUE TITLE
Both fill and stroke are being used on table sort and pagination icons with magna upgrade

### ISSUE THREAD

**Issue by sabrinamokerji** [cisco-sbg-ui/magna-react#206]
I'm going to assume the sort icons shouldn't have both? I haven't seen any Magnetic table icons look like this

<img width="1867" alt="Screenshot 2023-03-01 at 1 36 35 AM" src="https://user-images.githubusercontent.com/12389266/222074261-87256fa6-7fca-49b2-8cca-89ba4f45495a.png">

<img width="213" alt="Screenshot 2023-03-01 at 1 39 57 AM" src="https://user-images.githubusercontent.com/12389266/222074823-692f4f0d-c2b4-4da7-ad6c-2b71f81d14b3.png">

This can be seen on the demo site too: https://magna-react.vercel.app/components/data-table

**Comment by rwharrisjr** [comment]
Missed this in my mapping. These icons are not part of phosphor, unlike the majority of what Magnetic designates we use. 

Resolved in #209
