### ISSUE TITLE
Several missing icons from magna upgrade

### ISSUE THREAD

**Issue by sabrinamokerji** [cisco-sbg-ui/magna-react#207]
I noticed that the heading and quote icons no longer exist with the new magna upgrade to beta19. We used these in the toolbar for our markdown editors. 

These icons were named `textH` and `quotes`. They don't show on the magna demo site anymore either. 

I also noticed the **disposition icons** (`malicious`, `suspicious`, etc.) and `gitMerge` icons are missing now too. Disposition icons are pretty important 😅  We won't be able to upgrade magna without them.

Was the removal intentional? And if so,  is there a list of all icons that were removed?

Icons **after** magna upgrade for markdown editor:

<img width="928" alt="Screenshot 2023-03-01 at 1 56 59 AM" src="https://user-images.githubusercontent.com/12389266/222078439-dd3c698c-1a03-4312-9a6f-cb9eaf7eb172.png">

Icons **before** magna upgrade for markdown editor:

<img width="930" alt="Screenshot 2023-03-01 at 1 47 23 AM" src="https://user-images.githubusercontent.com/12389266/222078014-f55deed0-48df-4889-bffa-7469fc3269af.png">

**Comment by sabrinamokerji** [comment]
Also noticed the `gitMerge` icon is missing now too

**Comment by rwharrisjr** [comment]
Not intentionally removed. The current set is based on a list from UX. I'll add back in any missing icons.
