### ISSUE TITLE
Breadcrumb arrow is different color than text

### ISSUE THREAD

**Issue by sabrinamokerji** [cisco-sbg-ui/magna-react#218]
**Describe the bug**

The magna upgrade changed the bread crumb arrow to no longer be the same color as the breadcrumb text

<img width="99" alt="Screenshot 2023-03-01 at 6 18 02 PM" src="https://user-images.githubusercontent.com/12389266/222297238-84b1e98b-ba9b-4b46-a736-ed9677862bd0.png">

**Comment by rwharrisjr** [comment]
Good eye.
