### ISSUE TITLE
Disposition icons throwing invalid DOM property warning for `xmlns:xlink`

### ISSUE THREAD

**Issue by sabrinamokerji** [cisco-sbg-ui/magna-react#222]
**Describe the bug**

When using disposition icons in the UI, a console warning displays that says "Warning: Invalid DOM property `xmlns:xlink`. Did you mean `xmlnsXlink`?"

<img width="1431" alt="Screenshot 2023-03-01 at 9 09 51 PM" src="https://user-images.githubusercontent.com/12389266/222321427-3ea982fa-2dec-46cd-97b9-11b636c9b36c.png">

**Comment by wlorand3** [comment]
A potential JSX friendly fix would be to use xmlnsXlink
https://stackoverflow.com/questions/53840684/react-svg-xmlnsxlink-identifier-expected

magna-react files affected:
dispositions/clean.svg, common.svg, unknown.svg
