### ISSUE TITLE
Disabled textareas should allow pointer-events

### ISSUE THREAD

**Issue by keweeks** [cisco-sbg-ui/magna-react#233]
There is a general css rule that sets:

```
.a-app .disabled, .a-app [disabled], .a-app[disabled] {
    cursor: not-allowed;
    pointer-events: none;
}
```

but this is not ideal behavior in many cases. For instance, if you have a teaxtarea that has content but is disabled, the user cannot even scroll the content. 

<img width="299" alt="Screenshot 2023-03-02 at 2 39 46 PM" src="https://user-images.githubusercontent.com/33638380/222576016-0cb7b958-a8d4-49c5-86db-dd79fb43fd8e.png">

**Comment by rwharrisjr** [comment]
@keweeks As per the above comment, the `readOnly` prop on `ATextarea` seems to do what you're looking for.
