### ISSUE TITLE
Update Tag "Status" colors to match Magentic

### ISSUE THREAD

**Issue by Graham187K** [cisco-sbg-ui/magna-react#243]
Hi,
Would it be possible to update the available status Tag colors to match Magnetic Figma?
I noticed this when I was interested in using a Tag for a Positive and Negative status tags.

Magnetic Figma
https://www.figma.com/file/oVZWatImEIbl1c8sjdGxi0/%F0%9F%A7%B2--Magnetic-Design-Library?node-id=5259%3A38496&t=KQe6fik0dDYrc0u4-0

![image](https://user-images.githubusercontent.com/22437616/223183731-55957a13-3b17-47c1-ae22-b87088213635.png)

Magna-React Docs:
![image](https://user-images.githubusercontent.com/22437616/223184040-1bfa2963-c4da-4451-b58f-229eda6cfcd7.png)

![image](https://user-images.githubusercontent.com/22437616/223184168-9d3d94dd-3743-4ef8-adfe-6251711b6d07.png)

**Comment by rwharrisjr** [comment]
I'll check with the magnetic team and see what the current guidance is. https://www.figma.com/file/oVZWatImEIbl1c8sjdGxi0/branch/yU3qYkj6T2kfN4XYtUkEeD/%F0%9F%A7%B2--Magnetic-Design-Library?node-id=33305%3A351970&t=XG6IBn9DKtzHZHrQ-0 (which appears to still be an active design file) shows the positive as blue. 

I'll update when I have confirmation on what the colors should be now, until they change again.

**Comment by rwharrisjr** [comment]
This seems to be the current token files with colors. Positive is showing as green, rather than the previous blue.

https://www.figma.com/file/YkDzHVFiiL61KrRBPCznSI/Magnetic-Theme-Light?node-id=1467%3A6581&t=qHnNZJRqA0erbXC0-0
