### ISSUE TITLE
Shell app header covers top of modal

### ISSUE THREAD

**Issue by sabrinamokerji** [cisco-sbg-ui/magna-react#249]
When opening `AModal` in the shell app, the header appears over the overlay and the top of the modal is covered.

<img width="1899" alt="Screenshot 2023-03-06 at 8 30 36 PM" src="https://user-images.githubusercontent.com/12389266/223306342-6e9703c5-893b-49ff-8cb3-e2934d661189.png">

I'm not really sure if this is something that should be solved in the shell app or in manga-react. 

I tried playing around with it and saw a couple of things that fixed it.

1. Accounting for the header height in `.a-modal-container`. The modal gets positioned correctly if I add the following:
```
height: calc(100vh - 56px);
margin-top: 56px;
```
<img width="245" alt="Screenshot 2023-03-06 at 8 27 21 PM" src="https://user-images.githubusercontent.com/12389266/223305810-912fa912-20a2-4051-98ea-b4e0dcf69da1.png">

2. When I remove the `z-index: 2` style from the header component in the shell app. However, this breaks the header menu dropdowns since it makes them no longer visible over the MFE apps.

<img width="395" alt="Screenshot 2023-03-06 at 8 30 51 PM" src="https://user-images.githubusercontent.com/12389266/223305930-11b482b4-ec1e-4520-87a3-081c7a1c1e26.png">

I think the header should be shown *behind* the overlay regardless. If it did, we wouldn't have to worry about the modal being tucked underneath it. 

@trent-boyd @rwharrisjr thoughts?

**Comment by rwharrisjr** [comment]
@sabrinamokerji I think your CSS fix is correct, but it should go into the shell app. magna-react should be agnostic to whatever is consuming it.

**Comment by sabrinamokerji** [comment]
Opened an issue in the shell app for this - https://github.com/advthreat/securex-ui-shell/issues/142
