### ISSUE TITLE
Vertical ATabs using incorrect hover and dark theme colors

### ISSUE THREAD

**Issue by sabrinamokerji** [cisco-sbg-ui/magna-react#251]
### Hover state

When I look at the Magnetic components, they don't actually have a state with the side border gray in light theme like magna-react is using. The hover state shows the side border to use a lighter shade of blue, along with the text using this same color.

https://magnetic.cisco.com/0a43ab5cd/p/89dccd-tab/b/4152be

<img width="718" alt="Screenshot 2023-03-06 at 11 02 33 PM" src="https://user-images.githubusercontent.com/12389266/223325270-f974e474-360b-4f3b-b3a8-b347acb259f2.png">

https://www.figma.com/file/oVZWatImEIbl1c8sjdGxi0/branch/yU3qYkj6T2kfN4XYtUkEeD/%F0%9F%A7%B2--Magnetic-Design-Library?node-id=5259%3A38450&t=zahj6Vlx6kJKoqYX-0

### Dark theme colors

Magnetic has the active tab styled in blue in dark theme, but magna shows it in light gray:

https://www.figma.com/file/oVZWatImEIbl1c8sjdGxi0/branch/yU3qYkj6T2kfN4XYtUkEeD/%F0%9F%A7%B2--Magnetic-Design-Library?node-id=33305%3A352429&t=ekz0nyiAsgaSC86N-0

**Magnetic**:

<img width="724" alt="Screenshot 2023-03-07 at 12 14 06 AM" src="https://user-images.githubusercontent.com/12389266/223336373-dd71cd2b-498d-45eb-af2e-e8fbba7f66ba.png">

**Magna-react**:

<img width="221" alt="Screenshot 2023-03-07 at 12 14 38 AM" src="https://user-images.githubusercontent.com/12389266/223336469-20bd441b-8708-42d1-b89f-ec841bd7ce16.png">

**Expected behavior**

~- The selected state should be applied as soon as the user clicks the tab. They shouldn't have to double-click.~
- The hover state styling should also have a lighter blue border instead of gray.
- Dark theme colors should match Magnetic.

**Environment (please complete the following information):**

Version: `1.0.0-beta.25`

**Additional context**

If it helps, here is the commit I made to switch from AStepper to ATabs - https://github.com/advthreat/incident-manager/commit/34b30f486d91d16d7ff04c44bbd738db482e8bda

Staging branch: https://securex-ui-incidents-int-git-127-response-ui.securex-preview.app/incidents/incident-57652431-59b2-4642-acd8-6879db32b224/response

**Comment by sabrinamokerji** [comment]
@rwharrisjr It looks like my typo with `tabkey` needing to be `tabKey` fixed the weird "sometimes active" state. So this issue should only still concern the hover and dark theme styles 👍

**Comment by rwharrisjr** [comment]
The dark theme appears to be correct, blue when the tab is selected, and gray on hover
From the figma, the hover color is:
<img width="267" alt="Screenshot 2023-03-09 at 2 14 04 PM" src="https://user-images.githubusercontent.com/23561587/224145333-742d50f3-6d5d-47f9-8ed3-e1a16703a701.png">


Adjusting the light theme to make light blue on hover.

**Comment by sabrinamokerji** [comment]
@rwharrisjr I meant that the active text color in dark theme is incorrect, not the border. The active text color is supposed to be the same blue as the border in dark theme, but magna leaves it gray
