### ISSUE TITLE
Add the `dots-three-vertical` icon

### ISSUE THREAD

**Issue by vdineva** [cisco-sbg-ui/magna-react#272]
Please add the `dots-three-vertical` icon to the set of icons Magna-React supports

Magna-react currently has `dots-three` and `dots-three-outline` versions. 
For the vertical variant - it seems to be only the `dots-three-outline-vertical` version. It would be nice to have the `dots-three-vertical` icon for consistency

<img width="1056" alt="Screenshot 2023-03-09 at 11 40 09" src="https://user-images.githubusercontent.com/791418/224094626-40597a8c-0d35-4751-8909-8b8bf1d1d636.png">

**Comment by rwharrisjr** [comment]
Resolved by #274
