### ISSUE TITLE
ATextArea validation styling

### ISSUE THREAD

**Issue by Graham187K** [cisco-sbg-ui/magna-react#281]
Hi,

Wondering if the validation state for `ATextArea` can be updated.
Noticing a couple of differences between our Figma specs and the actual:

- When the char limit is reached, the "hint" text, i.e. character count, disappears and instead the error notification is shown. Could the char count be left in place?
- There is not enough top-margin between the notification and the text-area... but this might just be because the hint is not longer visible.
- Width of notification is dictated by it's content.

**Actual:**
![image](https://user-images.githubusercontent.com/22437616/224368859-0aff6beb-9a95-41df-b670-cc4edff99579.png)

**Expected:**
![image](https://user-images.githubusercontent.com/22437616/224368550-57ca18e7-398e-482e-b0af-7959c3d81a18.png)

**Comment by rwharrisjr** [comment]
The behavior I'm seeing is that the hint doesn't disappear, but gets set to an `AAlert`. 

#282 adds two properties to enable the desired behavior.

On `ATextarea` (or anything that uses `AFieldBase`):

- `hintUsesValidationState` - set to false to display hint as text

On `AAlert` (used by `AHint` now):

- `fitContentWidth` - unsets the 100% width on the alert element.
