### ISSUE TITLE
APanel inconsistencies with magnetic 

### ISSUE THREAD

**Issue by mvelkCisco** [cisco-sbg-ui/magna-react#288]
Magnetic provides 2 types of "cards", "basic" and "container": https://magnetic.cisco.com/0a43ab5cd/p/60f4a1-card/b/97571f

These differ not just in border but also in padding, border radius, etc.

Magna-react has `APanel` with `borderless` prop with default `null`.

Looking through the apps, most are using the bordered version (default) for almost everything, but should be using "container" type for most of the cards that define the page layout: https://magnetic.cisco.com/0a43ab5cd/p/60f4a1-card/b/918302

Honestly I'm not sure how to out of this at this point. We could have had a `type=basic|container` prop with `container` default, but the `type` prop is taken by `Enum("default", "grey", "white", "dialog")`. 

We could change the defaults to resemble "container" more and add some prop to switch it to "basic" mode, and let the apps deal with the changes... I really don't know.

Thoughts?

**Comment by mvelkCisco** [comment]
Another option would be to deprecate `APanel` and implement `ACard` correctly from scratch (and use it internally everywhere).

**Comment by rwharrisjr** [comment]
At this point I think changing `APanel` would cause extra headache - that one has mutated over the past few months to fit the ever changing magnetic design and become unsynced with any design.

I like the idea of an `ACard` component. Starting from scratch with `ACard` and letting products swap when convenient would be better for devs I think.

**Comment by mvelkCisco** [comment]
Thanks, we might start working on it when we have some free capacity. 

And we were thinking to have a separate `ABasicCard` and `AContainerCard` rather than merging them together when they have such a different use cases. Or maybe `MBasicCard`/`MContainerCard`? :)

**Comment by rwharrisjr** [comment]
Probably best to stick with A* naming :). Basic card and container card seem reasonable.
