### ISSUE TITLE
Candidates to have a magnetic option - Round 1

### ISSUE THREAD

**Issue by alucigna** [cisco-sbg-ui/magna-react#30]
You can either set priority or limit your picks to 5 per round...we'll make quicker progress that way.

- [ ]     AAccordion                      
- [ ]     AAlert                          
- [ ]     AAutocomplete                   
- [ ]     ABadge                          
- [ ]     ABreadcrumb                     
- [ ]     AButton                         
- [ ]     AButtonGroup                    
- [ ]     ACheckbox                       
- [ ]     ACombobox                       
- [ ]     AContextualNotification         
- [ ]     AContextualNotificationMenu     
- [ ]     ADataTable                      
- [ ]     ADatePicker                     
- [ ]     ADialog                         
- [ ]     ADivider                        
- [ ]     AFieldBase                      
- [ ]     AFooter                         
- [ ]     AFooter                         
- [ ]     AHint                           
- [ ]     AIcon                           
- [ ]     AInputBase                      
- [ ]     AList                           
- [ ]     ALoader                         
- [ ]     AMenu                           
- [ ]     AMenuBase                       
- [ ]     APagination                     
- [ ]     APanel                          
- [ ]     APopover                        
- [ ]     AProgressbar                    
- [ ]     ARadio                          
- [ ]     ASelect                         
- [ ]     ASimpleTable                    
- [ ]     AStepper                        
- [ ]     ASlider                         
- [ ]     ASwitch                         
- [ ]     ATabs                           
- [ ]     ATag                            
- [ ]     ATextarea                       
- [ ]     ATextInput                      
- [ ]     ATimeline                       
- [ ]     AToast                          
- [ ]     ATooltip                        
- [ ]     ATree

**Comment by rwharrisjr** [comment]
These have mostly been addressed as requests come in, and will continue to be addressed on an as needed basis.
