### ISSUE TITLE
Add layout components to ADrawer

### ISSUE THREAD

**Issue by rwharrisjr** [cisco-sbg-ui/magna-react#304]
For easier DOM management it would be nice to have 

- ADrawerHeader
- ADrawerBody
- ADrawerFooter

`ADrawerHeader` could handle title text from a prop, as well as a close button. It could structure DOM so that text would never overlap an absolutely positioned close button.

These would be composable components similar to `AList` and `AListItem`

**Comment by brennarvo** [comment]
We can probably just port these over from Incident Manager since they're already created there.
