### ISSUE TITLE
Add Magnetic tiny loader variants

### ISSUE THREAD

**Issue by sabrinamokerji** [cisco-sbg-ui/magna-react#305]
**Is your feature request related to a problem? Please describe.**

Magna-react only provides `ADotLoader` to be used as a tiny loader for situations where a small loader needs to show (e.g. a table cell is updating, file is uploading, etc.) However, `ADotLoader` is not a part of Magnetic design. 

Magnetic shows tiny spinner icons and tiny progress loaders for these situations. Both `APageLoader` and `AProgressBar` don't provide these size variants. 

Additionally, `AProgressBar` doesn't have the ability to be used as an `indeterminate` progress bar.

**Example of indeterminate functionality:** https://mui.com/material-ui/react-progress/#linear-indeterminate

**Describe the solution you'd like**

Components to be created for Magnetic tiny loaders. We also need an indeterminate progress bar. It looks like Magnetic has 3 size variants for tiny loaders:

<img width="789" alt="Screenshot 2023-03-17 at 12 21 46 PM" src="https://user-images.githubusercontent.com/12389266/225977243-73e9f973-d3ef-49b9-8924-8ac1a15cad9e.png">

https://www.figma.com/file/oVZWatImEIbl1c8sjdGxi0/branch/yU3qYkj6T2kfN4XYtUkEeD/%F0%9F%A7%B2--Magnetic-Design-Library?node-id=33305-356318&t=HcH2DgmjJ1JKgLep-0

**Comment by mvelkCisco** [comment]
The added size variants don't seem to match what's defined in https://magnetic.cisco.com/0a43ab5cd/p/43b10f-progress-and-loading-indicators/b/016102. Also the overall design doesn't match. Adding #332 as a follow up.
