### ISSUE TITLE
Shrinked hint/validation alerts in inputs in 1.0.0-beta.29

### ISSUE THREAD

**Issue by mvelkCisco** [cisco-sbg-ui/magna-react#306]
Now:

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/51229231/226292656-c87d3066-9766-4eac-92c6-fc983d250ac8.png">

They used to be full width and it seems to be the same in the guidelines https://magnetic.cisco.com/0a43ab5cd/p/664407-form

<img width="334" alt="image" src="https://user-images.githubusercontent.com/51229231/226293094-887f9c0d-c2b8-4a30-b4ca-b05d26cfb366.png">

**Comment by mvelkCisco** [comment]
Caused by changes in https://github.com/cisco-sbg-ui/magna-react/pull/282 due to https://github.com/cisco-sbg-ui/magna-react/issues/281. Not sure what to do about it yet.

**Comment by mvelkCisco** [comment]
Based on https://magnetic.cisco.com/0a43ab5cd/p/664407-form and a discussion with a designer, I would propose to revert `AAlert` width unsetting by making `fitContentWidth` set to `true` by default. These alerts take the full width of the container in all the examples we could find in the guidelines.

Regarding the original issue https://github.com/cisco-sbg-ui/magna-react/issues/281, where the error seemed to wide, we would propose to actually keep the 100% width too. We don't think it's an issue from visual perspective. If you still prefer to make it shorter in this particular case, I would add a local override in the intelligence app (we could maybe add a prop to the input to be able to provide props for that alert).

@rwharrisjr & @Graham187K what do you think?

**Comment by rwharrisjr** [comment]
@mvelkCisco I put in a PR to remove the prop usage for input validation states. I think it should be up to the product to add an override in cases of very wide input elements on a case by case basis.

**Comment by mvelkCisco** [comment]
Looks like I misunderstood `fitContentWidth` yesterday. But thanks, that should work.
