### ISSUE TITLE
ADivider is 2px but probably should be 1px

### ISSUE THREAD

**Issue by mvelkCisco** [cisco-sbg-ui/magna-react#323]
We came across this in https://github.com/cisco-sbg-ui/magna-react/pull/322#discussion_r1147479570

The magna-react docs show `ADivider` used in the menu, so that's what products are doing (eg incident-manager). However based on figma the divider in menus should be 1px not 2px (incident-manager adds a global override to make all divides 1px).

I don't think a divider exists in magnetic, or I could not find it at least. All the separators I've seen on magnetic are 1px.  This doesn't look right:

<img width="175" alt="image" src="https://user-images.githubusercontent.com/51229231/227562349-db8005ff-9ff6-4f69-ad57-7e1a4829ab1a.png">

I would propose to just change it in magna-react to 1px.

**Comment by androche** [comment]
Closing as this has been resolved further in: https://github.com/cisco-sbg-ui/magna-react/pull/587
