### ISSUE TITLE
type_Organization icon should have a fill color + unable to pass `style` props to `AIcon`

### ISSUE THREAD

**Issue by sabrinamokerji** [cisco-sbg-ui/magna-react#333]
**Describe the bug**

The `type_Organization` icon in magna-react only has `stroke` color, but it's actually supposed to have a `fill` color as well. 

I also realized that I'm no longer able to pass direct styles to `AIcon` with the `style` attribute. I also noticed this around the time that all of the magna icons changed, but forgot to open an issue for it.

We currently have a feature where we're supposed to show this icon in the Response actions taken log for the button to view the workflow in Automate. This icon is being used because it's the same icon that is used in the shell left nav for the Automate app. The shell app correctly shows the icon with a fill color.

**Response mock-up**

<img width="286" alt="Screenshot 2023-03-31 at 2 12 46 PM" src="https://user-images.githubusercontent.com/12389266/229210312-1678c3e7-9613-4c14-ac53-b4cb9ff026d5.png">

**Shell app left nav**

<img width="280" alt="Screenshot 2023-03-31 at 2 13 03 PM" src="https://user-images.githubusercontent.com/12389266/229210293-767f06e4-daee-4139-93a8-cd5f2c5a909e.png">

However, when I use the icon in our app, it looks like this:

<img width="381" alt="Screenshot 2023-03-31 at 2 17 13 PM" src="https://user-images.githubusercontent.com/12389266/229210361-5b09f058-c793-4171-b453-af21c2a95da6.png">

It looks correct when I add `fill: currentColor` to the icon:

<img width="366" alt="Screenshot 2023-03-31 at 2 20 52 PM" src="https://user-images.githubusercontent.com/12389266/229210588-9460b4cb-0713-4e55-9138-1db73f95e20d.png">

**Comment by trent-boyd** [comment]
I think it should _only_ have a fill color or it will require one extra step to style. The stroke can also make the icon appear larger than it should be.

Also, I believe the two-tone icons in Magnetic are reserved for navigation only. Could be wrong there, but I've never seen an inline icon with two distinct colors.

**Comment by rwharrisjr** [comment]
The build script that makes the icons style-able got a little overzealous here. I'll clean it up so they'll appear correctly.

**Comment by rwharrisjr** [comment]
![Screenshot 2023-04-04 at 1 10 09 PM](https://user-images.githubusercontent.com/23561587/229880895-1dc65b6d-bf6a-4e14-ae86-8ce974810d8d.png)
![Screenshot 2023-04-04 at 1 10 39 PM](https://user-images.githubusercontent.com/23561587/229880902-a83c1a9c-fa7e-46d2-88af-8b9ee78badb5.png)
