### ISSUE TITLE
Media query helper classes don't apply styles in the same way as ACol. All larger viewports receive styles intended for smaller viewport due to `min-width`

### ISSUE THREAD

**Issue by sabrinamokerji** [cisco-sbg-ui/magna-react#334]
**Describe the bug**

Since the media query classes use `min-width`, styles get unexpectedly applied to all screen sizes above the target being used in the className. I noticed `ACol` also uses `min-width` though, but it seems the styles for the other viewports are removed from the stylesheet when it gets to those viewports for `ACol`

**Use case**

Given the code below, I would expect the classNames to only apply the styles with the breakpoints I'm providing, like how `ACol` handles this.

```
<AContainer fluid className="pa-0">
  <ARow noGutters>
    <ACol lg="8" md="12">
      <PanelComponent1 className"mr-lg-0 mx-md-0" />
    </ACol>
    <ACol lg="4" md="12">
      <PanelComponent2 className="ml-lg-0 mx-md-0" />
    </ACol>
  </ARow>
</AContainer>
```

However, `mx-md-0` is applied even at `lg` and `xl` viewports:

<img width="409" alt="Screenshot 2023-04-03 at 8 40 46 AM" src="https://user-images.githubusercontent.com/12389266/229528187-ae2e0c94-191f-4f2e-8815-803af6436b6d.png">

This prevents me from being able to use these classes since I need lg viewports to only remove margin from one side.

**Comment by rwharrisjr** [comment]
Changing behavior of these classes would likely lead to many unintended side effects. If needed we can work on a new class system, or leave it up to product to handle layout with other methods.
