### ISSUE TITLE
Consider limiting the Select option text

### ISSUE THREAD

**Issue by vdineva** [cisco-sbg-ui/magna-react#337]
In certain cases the options we display for dropdown menus are coming from user input and we can end up in a situation where the width of the option goes beyond the screen viewport:

<img width="1728" alt="Screenshot 2023-04-03 at 15 38 40" src="https://user-images.githubusercontent.com/791418/229610215-2050f00e-5853-4072-92cd-7a2ea90735a4.png">

Also, if the user were to select this long option - we may want to truncate the text so it fits on 1 line only
<img width="1329" alt="Screenshot 2023-04-03 at 15 40 37" src="https://user-images.githubusercontent.com/791418/229610553-fe6ed6a3-a0f8-4bac-8b0d-0f7ae9f48ed3.png">

Code to reproduce:
```
() => {
  const items = [
    {id: 1, name: "Bread, Cereal, Rice, and Pasta"},
    {id: 2, name: "Vegetables Vegetables Vegetables Vegetables Vegetables Vegetables Vegetables Vegetables Vegetables Vegetables Vegetables Vegetables Vegetables Vegetables Vegetables Vegetables Vegetables Vegetables Vegetables Vegetables Vegetables All the way"}
  ];
  const [selectedItem, setSelectedItem] = useState(items[2]);
  return (
    <div style={{minHeight: 220, minWidth: 250, marginRight: 20}}>
      <ASelect
        label="Food Group"
        items={items}
        itemText="name"
        itemValue="id"
        placeholder="Pick a Food Group"
        onSelected={(item) => setSelectedItem(item)}
        hint={`Selected Item: ${JSON.stringify(selectedItem)}`}
      />
    </div>
  );
}
```

**Comment by rwharrisjr** [comment]
https://github.com/cisco-sbg-ui/magna-react/pull/340 will add two new props to ASelect for opt-in handling of long content. In many cases the default behavior of the menu width being `min-width: max-content` is likely desired. The change allows for easy wrapping of string values for cases determined by the developer.
