### ISSUE TITLE
Tabs Component underline should be shorter

### ISSUE THREAD

**Issue by vdineva** [cisco-sbg-ui/magna-react#354]
In Magnetic the currently selected tab has the underline as wide is the text:
https://magnetic-react.cisco.com/?path=/story/core-tabs--horizontal (must be on VPN)
![Screenshot 2023-04-20 at 11 41 20](https://user-images.githubusercontent.com/791418/233417985-b99d2b00-6dd5-4b77-b6b6-6cd3d56ed8bd.png)

The magna-react implementation seems to add left/right padding which causes the underline to extend beyond the text:
<img width="901" alt="Screenshot 2023-04-20 at 11 44 43" src="https://user-images.githubusercontent.com/791418/233418609-6cd78e8f-e7a9-4abe-a408-94a1c171376c.png">

**Comment by androche** [comment]
Hmm @rwharrisjr with magnetics design, the tabs would be all different sizes as seen here.  Is that really want they were going for? 

![longTitle](https://user-images.githubusercontent.com/112431822/234376677-6bac5c38-2ecb-4077-883d-1a73c2f6ba1b.gif)

**Comment by androche** [comment]
Checked a couple other website out of curiosity and this is actually a common pattern these days. I'll push this update through!
