### ISSUE TITLE
Observations from EVO Incident List

### ISSUE THREAD

**Issue by Graham187K** [cisco-sbg-ui/magna-react#36]
Hi,

These are some observations from adding Magna-React to new Project Evo Incidents page.

![image](https://user-images.githubusercontent.com/22437616/203405122-65b002c3-6a22-44b3-b06f-c4ef758792b2.png)

**Medium Button Prop**
I think the `medium` (magna style) prop needs to be added to other form controls. Below is a screenshot of a button using the Magna style inline with a TextInput. Ideally these would all have the same spacing properties.

![image](https://user-images.githubusercontent.com/22437616/203406040-9c0965bb-0260-49b3-8db9-0479099680fc.png)

**Magna styles as default**
For components which have an optional Magna style. It would help for this to be the default style since going forward this should be the default styling. Otherwise there's potential for dev's to not add these unintentionally.

```
// Current Impl
<AButton>Submit</AButton> // <= Atomic
<AButton medium>Submit</AButton> // <== Magna

// Proposed
<AButton>Submit</AButton> // <= Magna
<AButton small>Submit</AButton> // <= Atomic
```

**Pagination**
Pagination in Magnetic is has some differences:
- "per page" text is changed.
- Per page input is now a dropdown
- Show pages as `first... prev, current, next...last` as numbered buttons
- Update icons.
- Remove "Skip to first and skip to last" buttons 

_Current_
![image](https://user-images.githubusercontent.com/22437616/203407564-8e13ff43-e6b6-4fce-b7c0-853b1524817a.png)

_Magnetic Zero height_
![image](https://user-images.githubusercontent.com/22437616/203407990-4d783835-d09b-4843-aea6-7d36ba3cd654.png)

https://www.figma.com/file/oVZWatImEIbl1c8sjdGxi0/branch/yU3qYkj6T2kfN4XYtUkEeD/%F0%9F%A7%B2--Magnetic-Design-Library?node-id=5247%3A39676&t=10HDUcOj0IoAgGBP-0

**Table Sort Icons**
Table sort icons need to be updated
![image](https://user-images.githubusercontent.com/22437616/203409422-f31d327f-1fff-4281-8036-0881cc945e5f.png)

![image](https://user-images.githubusercontent.com/22437616/203409492-99bd94f7-e290-48c1-a918-b12938d4c3cd.png)

Also, the table has a three sort states: `asc`, `desc` and `none`. When the table is in the `none` state, it still shows the `asc` icon while the users cursor is still over the table column header which was clicked. It creates a weird visual since it implies the column is sorted in ascending order when actually the table has reverted to it's default sort order.

I think it should either show no icon, or a similar icon to the third option in screenshot above, but both arrows use the lighter grey color.

**Publish Magna-React as NPM module**
Could a BETA version of the library be published to the repository?

It's a little awkward to over-write NPM modules. We're using Webpack 5 which has more aggressive cache strategies which tends to reset manual changes to `node_modules` often. Installing a BETA version via the repository would help a lot.

Thank you!

**Comment by rwharrisjr** [comment]
**Magna styles as default**
This package won't change defaults to magnetic styling - its purpose is a non-breaking drop in replacement for atomic-react. Changing default sizes/formats would lead to broken pages. 

**Table Sort Icons**
Sort icons and design matching has been addressed

**Pagination**
Will be addressed as part of the design review

**Comment by rwharrisjr** [comment]
I think everything in this issue has been addressed.
