### ISSUE TITLE
Create a `TooltipIfTruncated` component

### ISSUE THREAD

**Issue by vdineva** [cisco-sbg-ui/magna-react#371]
Currently the admin app in the monorepo has a component `TooltipIfTruncated`: https://github.com/advthreat/securex-ui-monorepo/blob/main/apps/admin/src/components/TooltipIfTruncated.js

and we need the same functionality in Device Insights. Can we have this component be part of magna-react so each app can easily re-use it?

https://github.com/cisco-sbg-ui/magna-react/assets/791418/cabd62cf-2f32-49a3-81a5-a9cbda892504

**Comment by vdineva** [comment]
* disclaimer: I'm not sure this existent `TooltipIfTruncated ` component is per Magnetic specs

**Comment by vdineva** [comment]
it seems it is: 
https://magnetic.cisco.com/0a43ab5cd/p/89dccd-tab/t/13e38f
https://magnetic.cisco.com/0a43ab5cd/p/632c0b-breadcrumb/t/06bfaf

**Comment by rwharrisjr** [comment]
Added functionality as a prop on `ATriggerTooltip`

**Comment by androche** [comment]
@vdineva just hoping you could verify if https://github.com/cisco-sbg-ui/magna-react/pull/394 is what you were looking for?  If so we can get that merged in for the next build.

**Comment by vdineva** [comment]
@androche  works like a charm. Thank you!

**Comment by rwharrisjr** [comment]
Available in `1.0.0-beta.46`
