### ISSUE TITLE
Close icon in search bar

### ISSUE THREAD

**Issue by annika1997** [cisco-sbg-ui/magna-react#375]
## Checklist

- [ ] Close icon to appear only when user types. 

## Expected Behavior
<img width="567" alt="image" src="https://github.com/advthreat/incident-manager/assets/85970597/c6eb157d-5777-4d5e-8ee5-ccebf0613e8e">

## Actual Behavior
<img width="1465" alt="image" src="https://github.com/advthreat/incident-manager/assets/85970597/d677abe0-3edf-4a27-9c74-6c1b29651107">

**Comment by NeelSaini** [comment]
Verified in rel v1.123
Do not have the permission to add "QA Verified " Label
