### ISSUE TITLE
Icon weight 

### ISSUE THREAD

**Issue by annika1997** [cisco-sbg-ui/magna-react#376]
**Describe the bug**
Following icons needs to have thicker border

- [ ] Arrow square out icon 
- [ ] Info icon 
- [ ] Close icon
- [ ] Magnifying glass icon
- [ ] Clock icon
- [ ] Pencil icon
- [ ] Add icon
- [ ] Download icon
- [ ] Trash icon

**Expected behavior (+svg files)**
![ArrowSquareOut](https://github.com/cisco-sbg-ui/magna-react/assets/85970597/740182d9-e850-43dc-96fa-724b9625c03e)
![Info](https://github.com/cisco-sbg-ui/magna-react/assets/85970597/29c68274-7964-4b5f-a7ab-ac3e4cd02619)
![MagnifyingGlass](https://github.com/cisco-sbg-ui/magna-react/assets/85970597/09cbcc4c-c214-433b-92c5-4665b72bb632)
![X](https://github.com/cisco-sbg-ui/magna-react/assets/85970597/e5500558-d0fc-4901-b8c3-2ccab6a2cd15)
![clock](https://github.com/cisco-sbg-ui/magna-react/assets/85970597/e60347b3-002f-4b9a-8e61-d8297b40eb25)
![PencilSimple](https://github.com/cisco-sbg-ui/magna-react/assets/85970597/56f950fc-603b-4b07-a145-d41aea014bb0)
![Plus](https://github.com/cisco-sbg-ui/magna-react/assets/85970597/f1c12f4e-1216-4f6a-afcd-1a6b04de76a8)
![Trash](https://github.com/cisco-sbg-ui/magna-react/assets/85970597/06debf72-d79f-449d-9486-f33f04234581)
![DownloadSimple](https://github.com/cisco-sbg-ui/magna-react/assets/85970597/a3c4a397-15c8-4d04-8b70-baf45567a9c8)

<img width="439" alt="image" src="https://github.com/cisco-sbg-ui/magna-react/assets/85970597/9259557a-f3e2-414a-9a12-9ed2001003b6">

**Screenshots**
<img width="151" alt="image" src="https://github.com/cisco-sbg-ui/magna-react/assets/85970597/e4081513-01fc-4a81-ae1a-fd000ee11223">
<img width="294" alt="image" src="https://github.com/cisco-sbg-ui/magna-react/assets/85970597/c0da296a-11ca-4d0f-a429-e515bec2fd42">
<img width="129" alt="image" src="https://github.com/cisco-sbg-ui/magna-react/assets/85970597/c5c69aa8-916e-47d4-9b39-1fb8ef32a1bc">
<img width="679" alt="image" src="https://github.com/cisco-sbg-ui/magna-react/assets/85970597/d91a2bfa-d205-484f-b98e-8a261b95d9a7">
<img width="201" alt="image" src="https://github.com/cisco-sbg-ui/magna-react/assets/85970597/637233d4-0e6d-4780-89b8-4548e7540d24">
<img width="500" alt="image" src="https://github.com/cisco-sbg-ui/magna-react/assets/85970597/13b4e409-cdf5-4429-9b10-9ad0f39a487a">

**Comment by annika1997** [comment]
Yup, changing everything to bold works

**Comment by rwharrisjr** [comment]
@derrick-snider Are you ok with swapping the icon set to phosphor bold? Can view what they'd look like in context here https://magna-react-duzo4x7ci.securex-preview.app/components/icon#gallery

Swapping all icons is a big shift, not sure if we want to adhere to magnetic's recommendation or go piecemeal

**Comment by derrick-snider** [comment]
It seems like that is what Magnetic wants.
