### ISSUE TITLE
`AModal`'s focus trap automatically focuses first focusable element regardless if it's semantically appropriate

### ISSUE THREAD

**Issue by MikkCZ** [cisco-sbg-ui/magna-react#396]
**Describe the bug**
`AModal`'s focus trap chooses the first focusable element and focuses it. However this is not always the right element to focus in terms of the semantics of the content.

**To Reproduce**
1. Have the following modal.
```js
export default function MyModal({isOpen}) {
  return (
    <AModal isOpen={isOpen} aria-labelledby="modalTitle" withFocusTrap>
      <APanel type="dialog">
        <APanelTitle id="modalTitle">TITLE</APanelTitle>
        <APanelFooter>
          <AButton tertiary>Tertiary</AButton>
          <AButton primary>Primary</AButton>
        </APanelFooter>
      </APanel>
    </AModal>
  );
}
```
2. Open this modal.

**Actual behavior**
The tertiary button is focused.

**Expected behavior**
Either no element is focused, or I can specify/override the element to get focused (possibly the primary button in this case).

**Screenshots**
<img width="212" alt="Screenshot 2023-05-19 at 9 18 49" src="https://github.com/cisco-sbg-ui/magna-react/assets/3941344/7e93807e-106e-4ac0-a14a-1802513d872a">

**Comment by MikkCZ** [comment]
A viable solution for both this and #395 would propably be to (optionally) skip the autofocus to the first focusable element that is now part of the focus trap.

**Comment by MikkCZ** [comment]
Another example, in https://magna-react.vercel.app/components/modal the autofocused element is the close icon, despite there is the primary button in the modal. Hitting enter right after the modal closes the dialog via the close icon, while te user might righfully expected they confirmed the primary action.

**Comment by mvelkCisco** [comment]
I would just again highlight that calling `.focus()` on a container div with `tabindex="-1"` inside the modal component (that wraps the modal or its content) is a typical solution I've also seen in other libraries before (instead of focusing any particular element passed in children). I didn't dig into any accessibility guidelines though.
