### ISSUE TITLE
Remove hover state from ATimeline and change blue color for dark theme

### ISSUE THREAD

**Issue by sabrinamokerji** [cisco-sbg-ui/magna-react#402]
**Related issues**
https://github.com/advthreat/incident-manager/issues/898
https://github.com/advthreat/incident-manager/issues/833

**Describe the bug**

ATimeline has a hover state that changes the background of the entire timeline item. This doesn't make sense because there may be no interaction associated with the timeline item, so no hover state should be used. This is also not a Magnetic pattern.

**To Reproduce**

1. Go to https://magna-react.vercel.app/components/timeline
2. Hover over a timeline item
3. Observe entire background color of timeline item changes color
4. Change theme to dark mode
5. Observe blue color does not change to the dark theme blue

**Expected behavior**

There should be no style change on hover of timeline items. The background color should not change.
The blue color used in the timeline should convert to the correct dark theme blue color.

**Screenshots**

<img width="809" alt="Screenshot 2023-05-19 at 3 46 48 PM" src="https://github.com/cisco-sbg-ui/magna-react/assets/12389266/6588a419-b0d6-43ee-9886-06072ca18bbd">

<img width="693" alt="Screenshot 2023-05-19 at 3 51 14 PM" src="https://github.com/cisco-sbg-ui/magna-react/assets/12389266/0c522fbb-f08c-48b9-b239-ed46dbbdf941">

**Comment by androche** [comment]
I'm going to also remove the margin's here - in practice it makes things look way too spaced out
![Screenshot 2023-05-24 at 12 14 40 PM](https://github.com/cisco-sbg-ui/magna-react/assets/112431822/4863e685-aa6d-4704-b0a7-6b36255dcf9c)
