### ISSUE TITLE
`AButton` with component prop still allows clicks when disabled

### ISSUE THREAD

**Issue by radesai21** [cisco-sbg-ui/magna-react#406]
**Describe the bug**
When using `AButton` with a `Link` component prop the disabled state still allows clicks.

Example from DI:

```tsx
import { Link } from 'react-router-dom';

<AButton medium component={Link} disabled={true} to="/some/path" onClick={() => console.log('clicked')}>
  Click Me
</AButton>
```

**To Reproduce**
1. Create a `AButton` component using `Link` passed in as a component prop & an onClick callback
2. Disable the button using `disabled={true}` prop
3. Notice the button has disabled styling
4. Click the button - notice log is still getting printed when disabled.

**Expected behavior**
The button should not allow clicking on it when disabled.

**Screenshots**
Example from DI:

https://github.com/cisco-sbg-ui/magna-react/assets/95231401/3dc6b880-41ba-413d-bdf6-5a9940bd54fd

**Environment (please complete the following information):**
 - Device: Mac
 - OS: macOS
 - Browser: Safari
 - Version: `1.0.0-beta.41`

**Additional context**
Unfortunately unable to give code snip to test in the magna playground since the reproduction steps depend on a `Link` component from a routing package.

**Comment by sabrinamokerji** [comment]
@androche @rwharrisjr curious if disabling pointer events will prevent tooltips from working on disabled buttons again as mentioned in this issue? https://github.com/cisco-sbg-ui/magna-react/issues/307

**Comment by rwharrisjr** [comment]
@sabrinamokerji if using `ATriggerTooltip` it should still work as expected on disabled buttons - https://magna-react.vercel.app/components/triggertooltip#on-a-disabled-element
