### ISSUE TITLE
`AButton` with `loading` prop should show loader and hide icon in button

### ISSUE THREAD

**Issue by vdineva** [cisco-sbg-ui/magna-react#409]
**Describe the bug**

In the `Loading state` section here: https://magnetic.cisco.com/0a43ab5cd/p/56608b-button
The specification says: "If there is an icon in the button, the loader replaces the icon."

**To Reproduce**
```
() => {
  const [loading, setLoading] = useState(false);
  return (
    <AButton onClick={() => setLoading(true)) loading={loading}>
        <AIcon left>edit</AIcon>
        Primary with Icon
      </AButton>
  );
}

```

**Expected behavior**
I would expect the spinner to replace the icon, i.e. the pen icon from the example code to be hidden

**Comment by rwharrisjr** [comment]
I think this has been addressed, but not put in a build yet. https://github.com/cisco-sbg-ui/magna-react/pull/384

**Comment by androche** [comment]
@rwharrisjr I was mentioning in there (unless i'm interpreting incorrectly) that both scenarios button with text and button with icon should have icons replaced with loaders.  Right now the buttons show both:
![Screenshot 2023-05-25 at 5 26 56 PM](https://github.com/cisco-sbg-ui/magna-react/assets/112431822/24f19cda-9bbe-4309-ac1d-2472f53e17f8)
