### ISSUE TITLE
`ATextInput` does not show the clear icon when re-mounted

### ISSUE THREAD

**Issue by MikkCZ** [cisco-sbg-ui/magna-react#423]
**Describe the bug**
When `ATextInput` is re-mounted, it calls the `reset` function which de-syncs the `hasValue` state regardless of the actual value.

**To Reproduce**
1. Have a page with a (with `clearable`) `ATextInput`.
2. Type something into the input.
3. Navigate to a different page (inside the React app).
4. Navigate back.
5. The input value is preserved, but the clear icon is not shown.

**Expected behavior**
The clear icon is always visible if there is any value in the input.

**Additional context**
Regression from https://github.com/cisco-sbg-ui/magna-react/pull/377.

**Comment by NeelSaini** [comment]
Verified in rel v1.123
Do not have the permission to add "QA Verified " Label
