### ISSUE TITLE
`ATextInput`'s clear icon causes the input to grow in width under certain conditions

### ISSUE THREAD

**Issue by MikkCZ** [cisco-sbg-ui/magna-react#424]
**Describe the bug**
When the clear icon renders after typing into an input, the whole input grows in width unless explicit width is set to a common wrapping element.

**Screenshots**

https://github.com/cisco-sbg-ui/magna-react/assets/3941344/380b9502-892a-4459-8411-5cd77cca249c

**Additional context**
Regression from https://github.com/cisco-sbg-ui/magna-react/pull/377. Before the clear icon was always either present or missing, but it never was not being added/removed on-demand.

**Comment by MikkCZ** [comment]
NOTE: on the screen recording above, that particular input was actually expected not to be `clearable` at all. That will be addressed in https://github.com/cisco-sbg-ui/magna-react/issues/422.

Nevertheless this specific issue affects any input that has the `clearable` prop `true` and its wrapping element or itself does not have a fixed width set.

**Comment by androche** [comment]
FYI went ahead and closed my PR for the absolute btn - although it fixed a few scenarios, there are a lot of options for appending various content which I didn't realize.

**Comment by androche** [comment]
Back at it!
