### ISSUE TITLE
`ATextInput`'s clear icon does not disapper when all input is deleted

### ISSUE THREAD

**Issue by MikkCZ** [cisco-sbg-ui/magna-react#425]
**Describe the bug**
When all input text is manually deleted from the input, the clear icon is still visible.

**To Reproduce**
1. Have a page with a (with `clearable`) `ATextInput`.
2. Type something into the input.
3. The clear icon shows up.
4. Delete the typed input by pressing backspace.
5. The clear icon is still there.

**Expected behavior**
The clear icon disappears when the input it empty, regardless how that has been achieved.

**Additional context**
Regression from https://github.com/cisco-sbg-ui/magna-react/pull/377.

**Comment by NeelSaini** [comment]
Verified in rel v1.123
Do not have the permission to add "QA Verified " Label
