### ISSUE TITLE
Make `medium` size variant the default for AButton... PLEASE

### ISSUE THREAD

**Issue by sabrinamokerji** [cisco-sbg-ui/magna-react#427]
Please, for the love of God, can we make the `medium` size variant the default for `AButton`? 😅  

It's causing so many inconsistencies across the XDR apps because developers don't realize they need to add it every time they show a button. I'm constantly having to remind people to add it.

Actually, can we just make everything that has a `medium` prop use that by default since that's the Magnetic default? I think there are some inputs/select/button groups, etc. that need this too.

I also think the Control Center and Administration apps are assuming this will happen at some point and haven't been adding the prop to any of their buttons.

**Comment by sabrinamokerji** [comment]
@rwharrisjr if we don't plan to do this anytime soon, we should probably let the apps like Control Center and Administration know so they can add the prop for consistency across XDR

**CC** @DarMontou @ChloeCookeWarren

**Comment by sabrinamokerji** [comment]
@ChloeCookeWarren Robert changing this will make all of the magna-react inputs and buttons the correct Magnetic size. This will only happen for the Control Center and Administration apps if they update to the latest magna-react version that Robert releases this in though. 

Before this, all of the buttons and inputs were using the old atomic sizes, which were much shorter with different padding. To get the Magnetic styles, the devs needed to add the `medium={true}` prop to the components. If they didn't then the buttons and inputs would be the wrong size (using Atomic styles).

It looks like all of your XDR Figma's are already using the new Magnetic button and input sizes, so your designs shouldn't need to change at all. UI will just need to update the library to get the changes.

You can see the difference with buttons in this example: https://magna-react.vercel.app/components/button#magnetized-left--re-skin-only-right

Magnetic button styles are shown on the left, when the `medium` prop is used. The right displays the atomic styled buttons with just the color changed, which is what the CC and Admin apps currently have.

**Comment by rwharrisjr** [comment]
Merged code for defaults here
