### ISSUE TITLE
[BUG] ADataTable row borders disappear when styles are compiled in different order

### ISSUE THREAD

**Issue by sabrinamokerji** [cisco-sbg-ui/magna-react#432]
## Describe the bug

When I run `v1.0.0-beta.44` locally, the table row borders can no longer be seen. When compiled on the server, they can be seen because the build just so happens to put the `.a-simple-table` styles after the `.a-data-table` styles.

It appears `border-collapse: separate` was recently added to `.a-data-table` in this PR: https://github.com/cisco-sbg-ui/magna-react/pull/421/files#diff-e1a307a5a2776f82bf6925d0461006f1365d434a9e7a5b82430d80758c5e059dR56

The styles are overriding each other depending on the order or compilation, which is very fragile and should be more specific or scoped to the component. We can't rely on compilation order to always be the same.

Also, `border-collapse: separate` never gets applied to `.a-data-table` when compiled on the server since `.a-simple-table` gets added afterward and overrides this. Is this style even needed? It appears this is the style that is causing the borders to disappear. When I uncheck this locally, the borders reappear. It doesn't appear that this style ever gets added when on the server because of the build order that's happening.

## To Reproduce

1. Go to https://github.com/advthreat/incident-manager and run and the app locally
2. Go to `/incidents`
3. Observe that the table row borders are missing
4. Inspect element and observe that the `<tr>` element has `border-collapse: separate;` applied to it
5. Observe `.a-data-table` is providing the `<tr>` style
6. Go to https://magna-react.vercel.app/components/data-table
7. Observe that table row borders are showing
8. Inspect element on a table row and observe that the `<tr>` element has `border-collapse: collapse;`
9. Observe that `.a-simple-table` is providing the `<tr>` style

## Expected behavior
Table row borders should always be visible. `.a-simple-table` and `.a-data-table` should not override each other based on the order they are compiled in.

### Local env with borders missing

<img width="1915" alt="Screenshot 2023-06-12 at 8 40 28 PM" src="https://github.com/cisco-sbg-ui/magna-react/assets/12389266/2d046737-8e9f-4c47-8e8f-5d9c006486cc">

### Magna-react docs showing compilation order reversed with borders showing

<img width="1912" alt="Screenshot 2023-06-12 at 8 46 37 PM" src="https://github.com/cisco-sbg-ui/magna-react/assets/12389266/dea67f8c-95b0-4754-ba1f-f701414060b3">

**Comment by androche** [comment]
@sabrinamokerji Yikes! No this isn't crucial at all -  It was a nice-to-have for sticky headers to maintain their bottom border on scroll, but I cant believe we didn't notice that it made the rest of the lines disappear!  Will remove that css asap and try to come up with something else.
