### ISSUE TITLE
ATag does not match Magnetic styling

### ISSUE THREAD

**Issue by sabrinamokerji** [cisco-sbg-ui/magna-react#440]
**Describe the bug**

The `ATag` component is using the wrong font-weight and padding/sizing for tags. We've been adding custom styles in incident-manager to make the tags match Magentic, but we shouldn't be doing this. We're getting more features with tags and sometimes devs don't realize the styles don't match.

**To Reproduce**

1. Go to https://www.figma.com/file/oVZWatImEIbl1c8sjdGxi0/branch/yU3qYkj6T2kfN4XYtUkEeD/%F0%9F%A7%B2--Magnetic-Design-Library?type=design&node-id=5259-38496&t=GxZXojWYahCagqpv-0
2. Observe Magnetic tag components
3. Go to https://magna-react.vercel.app/components/tag
4. Observe that the magna-react tags have the incorrect font-weight and padding/sizing

Can we also add the different size variants for Magnetic tags please?

https://magnetic.cisco.com/0a43ab5cd/p/716124-tag

**Comment by rwharrisjr** [comment]
Font weight resolved by https://github.com/cisco-sbg-ui/magna-react/pull/442

**Comment by androche** [comment]
Question for all,

I noticed magna didn't initially provide the out-of-box icon for statuses.  I think it would make sense to update that, but realize that would be a breaking change since I assume people have been adding their own.  Just trying to gauge how useful that would be for teams in the immediate.


![Screenshot 2023-06-16 at 9 43 40 AM](https://github.com/cisco-sbg-ui/magna-react/assets/112431822/cb9e6611-fbc5-4b57-b2e2-b2efa49b00a6)
![Screenshot 2023-06-16 at 9 44 06 AM](https://github.com/cisco-sbg-ui/magna-react/assets/112431822/bf5d5624-707b-41e5-9276-d7facae4aa82)

**Comment by androche** [comment]
Also just noticed the colors are wrong after posting that which would need to be fixed as well.  lol

**Comment by androche** [comment]
(Please disregard last image above) ^ Search around a bit more and found another iteration of the statuses.

![Screenshot 2023-06-16 at 9 52 51 AM](https://github.com/cisco-sbg-ui/magna-react/assets/112431822/42bc032b-e2a2-4113-bbc4-37b9a4e3c2c1)

**Comment by androche** [comment]
Following up:  Probably something many know already, but there are some purposeful and accidental style variations  in designs between tag elements so the `ATag` will need a bit of work to tease all this out.  A few examples below. It will introduce some new props and breaking changes.  If its possible, it would be safer for teams to keep their workarounds and wait until after GA to adopt these changes coming in.  

**Tag without icon vs. tag with icon:**
12px side padding
![Screenshot 2023-06-16 at 1 17 10 PM](https://github.com/cisco-sbg-ui/magna-react/assets/112431822/448d5caf-20ec-4ac0-a603-d69264f3356c)
8px side padding
![Screenshot 2023-06-16 at 1 17 19 PM](https://github.com/cisco-sbg-ui/magna-react/assets/112431822/dac53894-fc2a-4e53-a64b-db1611cfe4ad)
except for binary which is 12px
![Screenshot 2023-06-16 at 12 58 30 PM](https://github.com/cisco-sbg-ui/magna-react/assets/112431822/7229e68b-ae13-40f5-8375-6289f2aa86b9)



**Status tags vs. a-tag with an icon**.  
Medium tag - icon size differences
![Screenshot 2023-06-16 at 12 44 04 PM](https://github.com/cisco-sbg-ui/magna-react/assets/112431822/599a4961-31df-4eee-830e-14d9811b4025)
![Screenshot 2023-06-16 at 12 44 18 PM](https://github.com/cisco-sbg-ui/magna-react/assets/112431822/6906b873-941a-43f1-b940-3110729f3ab6)

**Status tag v. binary tag**
Icon and padding size
![Screenshot 2023-06-16 at 12 58 37 PM](https://github.com/cisco-sbg-ui/magna-react/assets/112431822/44b2d051-c252-46db-9c42-a47a4533c027)
![Screenshot 2023-06-16 at 12 58 30 PM](https://github.com/cisco-sbg-ui/magna-react/assets/112431822/c49818b5-9242-4b6e-91c4-eaeb0052d014)
