### ISSUE TITLE
Add binary tag style to magna-react

### ISSUE THREAD

**Issue by paulina1211** [cisco-sbg-ui/magna-react#441]
**Is your feature request related to a problem? Please describe.**
Magna-react doesn't include the "binary tag" style available in the magnetic design system, and this tag style is needed in Control Center for XDR. 

**Describe the solution you'd like**
Please add the binary tag style to magna-react: 
<img width="539" alt="image" src="https://github.com/cisco-sbg-ui/magna-react/assets/64498448/f12871c3-4529-479d-9c29-17847da0e629">

**Describe alternatives you've considered**
We're using regular tags without the double circle icon right now, but including the double circle and empty circle icons is a big improvement in terms of accessibility since it adds another visual cue aside from color for colorblind users. 

**Additional context**

n/a

**Comment by androche** [comment]
Noting this will be addressed in https://github.com/cisco-sbg-ui/magna-react/issues/440

**Comment by androche** [comment]
Completed in #440
