### ISSUE TITLE
Clear icon is already there before typing the input text on all of the intelligence sub pages

### ISSUE THREAD

**Issue by NeelSaini** [cisco-sbg-ui/magna-react#445]
ENV: TEST

<img width="1324" alt="Screenshot 2023-06-19 at 5 22 22 PM" src="https://github.com/cisco-sbg-ui/magna-react/assets/44818630/6c13fe6b-3491-4134-a0d3-3dc0ea7a8620">

**Comment by androche** [comment]
@NeelSaini It looks like intelligence is still on magna version 1.0.0-beta.41 and needs to update to the latest version. A fix for that went in on beta.44.   Would you prefer to close or transfer the issue?
