### ISSUE TITLE
ASelect does not respect `medium={false}` prop

### ISSUE THREAD

**Issue by vdineva** [cisco-sbg-ui/magna-react#450]
If I pass in `medium={false}` to a `<ASelect` - it does not respect it - notice the `a-input-base--medium` css class
<img width="1604" alt="Screenshot 2023-06-22 at 16 44 32" src="https://github.com/cisco-sbg-ui/magna-react/assets/791418/6f6f4001-87e9-4c5f-87b7-f7ebbb290852">

code to reproduce:
```
() => {
  const items = [
    {id: 1, name: "Bread, Cereal, Rice, and Pasta"},
    {id: 2, name: "Vegetables"},
  ];
  const [selectedItem, setSelectedItem] = useState(items[2]);
  return (
        <ASelect
        medium={false}
        label="Food Group"
        items={items}
        itemText="name"
        itemValue="id"
        placeholder="Pick a Food Group"
        onSelected={(item) => setSelectedItem(item)}
        hint={`Selected Item: ${JSON.stringify(selectedItem)}`}
      />
  );
}
```

This bug is observed in v1.0.0-beta.47

**Comment by androche** [comment]
@vdineva I posted this on chat, but adding here as well fo reach!  It looks like you would need to add what size you were looking for instead `small` or `large`.  Since medium is the default, it doesn't know which one to pick out of the other two.

**Comment by vdineva** [comment]
@androche thank you!
The documentation may need to be updated then:
<img width="1595" alt="Screenshot 2023-06-23 at 8 41 52" src="https://github.com/cisco-sbg-ui/magna-react/assets/791418/72b6fe9e-c8b1-4308-a682-777f36e243bd">

**Comment by androche** [comment]
Thanks for pointing that out! I'll sneak it into another PR right now.
