### ISSUE TITLE
MultiSelect component tags seem too large

### ISSUE THREAD

**Issue by vdineva** [cisco-sbg-ui/magna-react#458]
No matter which size is picked-  they all seem the same and a bit loo large
<img width="1142" alt="Screenshot 2023-07-06 at 15 25 15" src="https://github.com/cisco-sbg-ui/magna-react/assets/791418/bad2d163-81c7-44c2-9e57-251ae3cf7781">

- `medium` and `large` props are not mentioned in the `[MultiSelect Props](https://magna-react.vercel.app/components/multiselect#multiselect-props)` section

- a minor detail: when the dropdown is open - the chervon should change its direction
*screenshots are from https://magnetic-react.cisco.com/?path=/story/core-select-multiselect--multi-select-default
![Screenshot 2023-07-06 at 15 28 31](https://github.com/cisco-sbg-ui/magna-react/assets/791418/dc51d8d1-6363-46b4-98b4-ed9a6368d5e9)
![Screenshot 2023-07-06 at 15 28 25](https://github.com/cisco-sbg-ui/magna-react/assets/791418/70b9e38b-a0ae-41fd-8a0a-9058621d787c)

**Comment by rwharrisjr** [comment]
I think this will be resolved with the line height updates in #457
