### ISSUE TITLE
Copy To Clipboard Component

### ISSUE THREAD

**Issue by radesai21** [cisco-sbg-ui/magna-react#464]
**Is your feature request related to a problem? Please describe.**
Magnetic Documentation provides designs for a `copy-to-clipboard` component that is a button with a hover tooltip & opens a popover confirmation on click/successful copy. 

**Describe the solution you'd like**
A generic component all XDR MFE's can reuse for copying text to the clipboard.

**Describe alternatives you've considered**
We could create our own using magna-react components (`ATooltip`, `APopover`, and `AButton`) but it would not allow other teams outside of DI to use it for consistency between apps. 

**Additional context**
Note that the magnetic documentation mentioned below uses a `tertiary` button with grey stroke for the icon but in magna-react `tertiary` buttons get a blue stroke.

Magnetic References
- [Magnetic Documentation - Copy To Clipboard](https://zeroheight.com/0a43ab5cd/p/73fcef-copy-to-clipboard)
- [Figma Magnetic Components - Copy To Clipboard](https://www.figma.com/file/oVZWatImEIbl1c8sjdGxi0/%F0%9F%A7%B2--Magnetic-Design-Library?type=design&node-id=93515-113494&mode=design&t=3IJjmlo6nIzZbr06-4)

**Comment by rwharrisjr** [comment]
Looks like the docs use `tertiary` for inline next to content, and `tertiaryAlt` inside tables. Both options will be available on the component.
