### ISSUE TITLE
Label for `<DateRangePicker />` component 

### ISSUE THREAD

**Issue by vdineva** [cisco-sbg-ui/magna-react#477]
It would be really nice if the `<DateRangePicker />` component has support for a label that upon clicking it would open up the calendar

**Comment by androche** [comment]
@vdineva Could you share an example of what this would look like.  Do you mean two labels above the input - one above startDate/endDate?

**Comment by vdineva** [comment]
I think just 1 label may be sufficient
Something like this - but not sure if it follow Magnetic guidelines:

https://github.com/cisco-sbg-ui/magna-react/assets/791418/2b8c6ad4-d31b-43cd-a7ca-5faffe81e208

**Comment by androche** [comment]
Oh I see - thanks for sharing this. Looks like I just totally ignored it in the mockup. :)   

![Screenshot 2023-08-02 at 2 41 40 PM](https://github.com/cisco-sbg-ui/magna-react/assets/112431822/17d28468-647f-41bf-a5a4-c8b767638ab0)
