### ISSUE TITLE
"More" overflow functionality for page-level tabs

### ISSUE THREAD

**Issue by paulina1211** [cisco-sbg-ui/magna-react#490]
**Describe the bug**
Magna-react currently has carats to scroll between tabs when there are many of them. However, magnetic has updated the design to instead have a "more" button with a dropdown to handle overflow. Please update magna-react to reflect the updated guidelines from magnetic, especially since the current scrolling carats aren't aligned with the text.

**Screenshots**
Magna-react overflow behavior (storybook and in XDR Control Center):
<img width="607" alt="image" src="https://github.com/cisco-sbg-ui/magna-react/assets/64498448/58207e76-e9bc-45f3-91cc-7ad0e87613cd">

<img width="663" alt="image" src="https://github.com/cisco-sbg-ui/magna-react/assets/64498448/ebb8f34d-5f6b-4249-a325-1cb1d0965571">

Magnetic guidance from website:
<img width="883" alt="image" src="https://github.com/cisco-sbg-ui/magna-react/assets/64498448/e945df2a-990d-475a-a1a2-be8b3ac3cac8">

**Additional context**

[magnetic tab overflow storybook link](https://magnetic-react.cisco.com/?path=/docs/components-tabs-tabs--secondary-overflow)

[magnetic design website, tabs ](https://magnetic.cisco.com/0a43ab5cd/p/89dccd-tab/b/54b046)

**Comment by paulina1211** [comment]
I asked magnetic if they were planning on changing this component anytime soon and it seems the answer is no, so efforts to update this style in magna-react wouldn't be wasted
<img width="777" alt="image" src="https://github.com/cisco-sbg-ui/magna-react/assets/64498448/aab8411f-d484-4732-aa52-741dae204ae7">

**Comment by androche** [comment]
This is back in research from UX

**Comment by androche** [comment]
Did not hear back from UX so moving forward with "secondary" as default and hiding the bottom bar on secondary to more closely match what is seen on XDR today.
