### ISSUE TITLE
[BUG] Headings and spacing units are still using atomic styles

### ISSUE THREAD

**Issue by sabrinamokerji** [cisco-sbg-ui/magna-react#499]
## Related issues
https://github.com/advthreat/incident-manager/issues/1020#issuecomment-1681570085
Incidents https://github.com/advthreat/incident-manager/issues/1020
Assets https://github.com/Cisco-PosaaS/oak/issues/8473
Automate https://jira-eng-sjc1.cisco.com/jira/browse/NEXTG-25678
Intell https://github.com/advthreat/intelligence/issues/224
Mono https://github.com/advthreat/securex-ui-monorepo/issues/1182

## Description

Magna-react components are not using correct spacing units or line-heights. Because of this, dev in each app has tried to add their own styles to get headings to look like mock-ups and it has caused all XDR headings to have inconsistent spacing.

We looked into fixing this ourselves in our own app when UX opened [this issue](https://github.com/advthreat/incident-manager/issues/1020), but found that it would require a very hacky workaround of overwriting styles of multiple magna-react components. (h1 line-height, margin, a-container padding, etc.) This would cause even more inconsistency. The correct place to fix this is in magna-react. The spacing units, line-height, margins, padding, helper classes, etc. all need to be using Magnetic spacing units.

The magna-react [helper classes](https://magna-react.vercel.app/components/app#helper-classes) are added in increments of `5px`, which is not the spacing unit that [Magnetic uses](https://magnetic.cisco.com/0a43ab5cd/p/96a662-layout/t/51d67b). Magnetic uses increments of `4px`.

## Magnetic references 

[Magnetic spacing](https://magnetic.cisco.com/0a43ab5cd/v/0/p/96a662-layout)
[Magnetic typography line height](https://magnetic.cisco.com/0a43ab5cd/p/4119aa-typography/b/46ab8c)

https://www.figma.com/file/03chsH5sSKnIKj3W3YVcWo/Magnetic-Component-Guidelines?node-id=4990%3A77963&mode=dev

## Screenshot

Arbitrary example using Control Center as baseline to show all different heading alignments throughout apps:

![XDR_headers_int_June_07_2023](https://github.com/advthreat/incident-manager/assets/429803/73adc17e-2675-48d2-8d6c-996cf027a741)

**Comment by sabrinamokerji** [comment]
FYI this has been designated as a high priority issue to resolve by PM and UX

**Comment by rwharrisjr** [comment]
Spacing adjustments have been made, and components to align headers have been delivered.
