### ISSUE TITLE
<DateRangePicker /> should display selected date in user's locale

### ISSUE THREAD

**Issue by vdineva** [cisco-sbg-ui/magna-react#518]
As a person in Europe (and rest of the world), when I select August 1 in the DateRangePicker component, I would expect the date to display in MM/DD/YYYY format - `01/08/2023` instead of `08/01/2023` in the screenshot below

![Screenshot 2023-09-13 at 11 41 21](https://github.com/cisco-sbg-ui/magna-react/assets/791418/027c78ac-c791-48b5-ac4d-f38ae58983c6)

related to https://github.com/cisco-sbg-ui/magna-react/issues/484

**Comment by androche** [comment]
Hi @vdineva I might be missing something, but for European format I see DD/MM/YYYY in the screenshot and when testing it appears correct.  

For example, format for London is DD/MM/YYYY

![Screenshot 2023-09-13 at 1 17 24 PM](https://github.com/cisco-sbg-ui/magna-react/assets/112431822/2f8a0203-a50a-48ef-830f-b14bd63bb815)

For Tokyo:
![Screenshot 2023-09-13 at 1 20 32 PM](https://github.com/cisco-sbg-ui/magna-react/assets/112431822/8683a2ec-0181-4b53-bc9a-09397e095ce5)

The format will change based on the users location.

**Comment by vdineva** [comment]
@androche yes, you are right - everything seems to work as expected. I got confused, closing this issue

**Comment by androche** [comment]
@vdineva Oh ok - Thanks for verifying!
