### ISSUE TITLE
Revisit APageContainer and adjust a-page-title margin

### ISSUE THREAD

**Issue by androche** [cisco-sbg-ui/magna-react#525]
**Two issues:**

1. There appears to be conflicting specifications for some spacing. Magnetic designs show `24px 36px 24px 24px` although there are some issues with header spacing here: https://github.com/advthreat/securex-ui-monorepo/issues/1182.  It was also brought up that certain groups agreed on `16px` all around.

We need to confirm the correct specifications for the page containers and headers. Also, it's been brought up that some teams (not in the usual channels) may not have received the request to update to these components.  Once we revisit/confirm with UX on the spacing issues, we should repost the announcement in all channels for reach.

2.  **APageContainer + APageTitle is rendering 48px - 24 in the admin section.**
(possibly visual breaking change for some)

<img width="222" alt="Screenshot 2023-09-22 at 9 34 30 AM" src="https://github.com/cisco-sbg-ui/magna-react/assets/112431822/ac1ac388-de60-4584-9fe4-cbe82245e7c1">
<img width="290" alt="Screenshot 2023-09-22 at 9 34 04 AM" src="https://github.com/cisco-sbg-ui/magna-react/assets/112431822/4b186385-ceff-49cc-b404-9a80b44b4a16"><br/>

<img width="214" alt="Screenshot 2023-09-22 at 9 34 48 AM" src="https://github.com/cisco-sbg-ui/magna-react/assets/112431822/eb879141-9055-48c9-828e-6f50c94ad808">

<img width="293" alt="Screenshot 2023-09-22 at 9 34 14 AM" src="https://github.com/cisco-sbg-ui/magna-react/assets/112431822/be327074-5309-4c2c-8e12-4ef74dfc69e4">

**Comment by trent-boyd** [comment]
So it turns out the `24px 36px 24px 24px` is correct, _but_ it should be padding instead of margin so it doesn't collapse with other margins and won't yield unexpected widths.

**Comment by androche** [comment]
Follow up, after catching up with Derrick we can implement 24px on all sides as Sabrina confirmed that the 36px was specifically for Meraki. 

For title we should follow:
![Screenshot 2023-09-25 at 9 15 19 AM](https://github.com/cisco-sbg-ui/magna-react/assets/112431822/93348118-64ab-4daa-af3f-115c3d49a151)

If we aren't already, we should take out any margin on content containers so 16px can be managed by the apps

**Comment by androche** [comment]
Resolved in https://github.com/cisco-sbg-ui/magna-react/pull/526
