### ISSUE TITLE
`ACheckbox` label alignment

### ISSUE THREAD

**Issue by radesai21** [cisco-sbg-ui/magna-react#538]
**Describe the bug**
When using the checkbox in a dropdown the label is not aligned vertically with the checkbox box. This could be happening outside dropdowns too, haven't found the best way to reproduce it outside of the dropdown

**To Reproduce**
1. Go to [magna-playground](https://magna-react.vercel.app/components/select)
2. Paste following code to make a mock dropdown with checkbox options in it:
```jsx
() => {
  const [role, setRole] = useState(null);
  const {isDark} = useATheme();

  return (
    <ASelect
      trunacteMenuItems
      itemTemplate={({ onClick, item, ...rest}) => (
        <AListItem {...rest}>
          <ACheckbox medium checked={item.text === role} onClick={(e) => { setRole(item.text); onClick(e); }}>
            {item.text}
          </ACheckbox>
        </AListItem>
      )}
      items={[
        { text: 'Read', disabled: true },
        { text: 'Write', disabled: true },
        { text: 'Admin', disabled: true }
      ]}
    />
  );
};
```
4. Inspect the menu items - notice the label is about `2px ~ 3px` pixels lower than the top of the box.
5. Notice the `a-checkbox__wrap` class has a `align-items: flex-start` style. If you manually update that to be `align-items: center` the checkbox will be aligned correctly with the label. 

**Expected behavior**
Ideally the label should be aligned vertically with the box

**Screenshots**

### With `align-items: flex-start`
![image](https://github.com/cisco-sbg-ui/magna-react/assets/95231401/ad3017ec-1a07-461e-8361-4791453fcd78)

### With `align-items:center`
![image](https://github.com/cisco-sbg-ui/magna-react/assets/95231401/cdbb8bcb-bc6c-4b3e-8660-8cf6c482c9df)

**Comment by rwharrisjr** [comment]
@radesai21 Is this a case that https://magna-react.vercel.app/components/multiselect could handle? It appears the labels are correctly aligned there, and would save custom code if you could use it.

**Comment by radesai21** [comment]
> @radesai21 Is this a case that https://magna-react.vercel.app/components/multiselect could handle? It appears the labels are correctly aligned there, and would save custom code if you could use it.

Ideally we would like to have it fixed for `ASelect` since we have quite a few of components still using it. We can address it from DI though
