### ISSUE TITLE
ADateRangePicker Component: UX improvements

### ISSUE THREAD

**Issue by vdineva** [cisco-sbg-ui/magna-react#546]
1. Can we please have the cursor as `default` (or `pointer`?) for the label field of the `<ADateRangePicker />` component

![Screenshot 2023-10-18 at 10 40 12](https://github.com/cisco-sbg-ui/magna-react/assets/791418/0c7a46bb-66b8-41b1-8d11-15b49e84357f)

2. When the user clicks on the `<ADateRangePicker />` component, we should highlight the field being selected from the calendar, e.g. in the screenshot below the first text field has the focus

![Screenshot 2023-10-18 at 10 36 42](https://github.com/cisco-sbg-ui/magna-react/assets/791418/016ebfba-3f76-46a8-90ef-c7abb659b052)

[ADateRangePicker](https://magnetic.cisco.com/0a43ab5cd/p/64eff0-date-picker/t/007e63)

**Comment by androche** [comment]
It used to highlight immediately, but looks like you have to click twice now - will take a look!
![Screenshot 2023-10-18 at 12 45 44 PM](https://github.com/cisco-sbg-ui/magna-react/assets/112431822/01c7d7f1-5a73-49f3-8789-283005c1a727)
