### ISSUE TITLE
Monospace font style

### ISSUE THREAD

**Issue by derrick-snider** [cisco-sbg-ui/magna-react#550]
### Description
Add a monospace font and font style component to magna-react so XDR/ Breach Protection suite can display monspace strings.

> ...Roboto Mono covers typographic monospaced needs and Source San Pro provides Asian and Cyrillic alphabets for language localization.
> Make that ID number clear. Use Roboto Mono to make networking values (MAC addresses and IP addresses) clearly distinguishable in key value pair displays and other content.

[Magnetic font source](https://magnetic.cisco.com/0a43ab5cd/p/4119aa-typography/b/412f4c/t/23d54f): "Roboto Mono (Monospace) Roboto Mono is under the Open Font License and can be used by any product across Cisco. No additional license needs to be procured." So magna-react can self host.

### Checklist
- [ ] add roboto for ip and mac strings
- [ ] add source sans pro for localization
- [ ] add styles and text component

### Images
see assets column here:
![image](https://github.com/cisco-sbg-ui/magna-react/assets/429803/e7a37114-10c3-4c32-8564-6fc7bc8d67bf)
4 sizes:
![image](https://github.com/cisco-sbg-ui/magna-react/assets/429803/2d51424a-7e0a-4b19-aaf0-fb6a78d0914b)

### Specs
This font style https://www.figma.com/file/oVZWatImEIbl1c8sjdGxi0/branch/YNkCw8yeaOOOuvxWtyRz4X/%F0%9F%A7%B2--Magnetic-Design-Library?type=design&node-id=99416%3A123065&mode=dev

`/* Paragraph/Monospace/P1 - XLarge Monospace */
font-family: Roboto Mono;
font-size: 18px;
font-style: normal;
font-weight: 400;
line-height: 24px; /* 133.333% */`

`/* Paragraph/Monospace/P2 - Large Monospace */
font-family: Roboto Mono;
font-size: 16px;
font-style: normal;
font-weight: 400;
line-height: 22px; /* 137.5% */`

`/* Paragraph/Monospace/P3 - Default Monospace */
font-family: Roboto Mono;
font-size: 14px;
font-style: normal;
font-weight: 400;
line-height: 20px; /* 142.857% */`

`/* Paragraph/Monospace/P4 - Small Monospace */
font-family: Roboto Mono;
font-size: 12px;
font-style: normal;
font-weight: 400;
line-height: 18px; /* 150% */`

### CC
@rwharrisjr @androche

**Comment by rwharrisjr** [comment]
Component to align https://magna-react.vercel.app/components/networkvalues
