### ISSUE TITLE
Allow setting a required flag without forcing the validation logic

### ISSUE THREAD

**Issue by lukaskral** [cisco-sbg-ui/magna-react#551]
It would be nice to be able to set the input field appear as required (showing the asterisk) without enabling the validation logic.

<img width="660" alt="Screenshot 2023-10-25 at 15 22 25" src="https://github.com/cisco-sbg-ui/magna-react/assets/1015328/7da3f186-4958-4c8e-9ba5-4c3209cfa8b3">

On a form we're using external validation tool and passing the validation messages to the form field like this:
```typescript
  <ATextInput
    label={t("playbookAssignmentDrawer.title")}
    required
    validationState={error ? ("danger" as const) : undefined}
    hint={error?.message}
  />
```

Unfortunately it doesn't play well with the `required` prop which adds a new layer of the field validation.

I experimented with the `rules` property which can override the default validation but unfortunately this causes an issue with the `validationState` property being overwritten:
```typescript
  <ATextInput
    label={t("playbookAssignmentDrawer.title")}
    required
    validationState={error ? ("danger" as const) : undefined}
    hint={error?.message}
    disabled={formState.isSubmitting}
    rules={[
      {
        key: "required",
        test: () => true
      },
      {
        test: () => error?.message ?? true,
        level: "danger"
      }
    ]}
  />
```
with this settings the field mostly works. The problem is, that the external validation is slower than the input validation so the error message is not populated when the test function of the second rule is triggered. This results in a weird states where error message is displayed with incorrect `level` as a normal message, not as an error . The current behavior is that if all the rules returns true the `validationState` is reset to the default value no matter what and I think it can't be easily overwritten from outside.

**Comment by rwharrisjr** [comment]
#557 adds a `skipValidation` prop to bypass validation
