### ISSUE TITLE
Create AI icon component

### ISSUE THREAD

**Issue by sabrinamokerji** [cisco-sbg-ui/magna-react#571]
## Description

Whenever AI-generated content is displayed within our app, we need to display an AI icon next to it to indicate this.

The AI icon should also display a tooltip when the user hovers over it. The default tooltip text should say: `This description was generated by Cisco AI`.

## Figmas

AI icon being used in XDR Incidents:

https://www.figma.com/file/jdGzGRcxgNjFDXIWmfEQZ3/XDR-110---Ai-Generated-Descriptions?node-id=5%3A102&mode=dev

Magnetic AI:

https://www.figma.com/file/xIcK0n9ErOnhvvev2WOvnH/%F0%9F%A7%B2-Magnetic-AI-Beta-Components?type=design&node-id=4-9&mode=design&t=hPkMSoMX3Nv2yd2k-0

## Screenshots

<img width="1680" alt="Screenshot 2023-11-15 at 11 49 17 AM" src="https://github.com/cisco-sbg-ui/magna-react/assets/12389266/ccbab922-8823-4225-ad95-f923623406f0">

<img width="1448" alt="Screenshot 2023-11-15 at 11 48 34 AM" src="https://github.com/cisco-sbg-ui/magna-react/assets/12389266/2f0319f9-c147-47f2-9f11-5178977d1b16">

<img width="1682" alt="Screenshot 2023-11-15 at 11 47 38 AM" src="https://github.com/cisco-sbg-ui/magna-react/assets/12389266/c6f0e74d-f3b5-4405-bb04-019bcd03faf8">

**Comment by robmorg** [comment]
@rwharrisjr - we need this for a pending UI change soon, can this be picked up ?
