### ISSUE TITLE
Info icon should be purple

### ISSUE THREAD

**Issue by guptar8jan** [cisco-sbg-ui/magna-react#574]
**Describe the bug**
Info icon should be updated to purple. https://magna-react.vercel.app/components/icon#gallery

**Expected behavior**
Purple background

cc @atjackson49

**Comment by androche** [comment]
@guptar8jan Yea this will be part of: https://github.com/cisco-sbg-ui/magna-react/issues/549

**Comment by androche** [comment]
Resolved in #549
