### ISSUE TITLE
Drawer is missing border under the header

### ISSUE THREAD

**Issue by guptar8jan** [cisco-sbg-ui/magna-react#577]
**Describe the bug**
Drawer component should have border under the header. https://magna-react.vercel.app/components/drawer

**To Reproduce**
I got this design from UX which seem to indicate a border under the header. It seems reasonable to have a border.
<img width="166" alt="image" src="https://github.com/cisco-sbg-ui/magna-react/assets/10874564/c4aa9120-154b-49ed-8f2b-f7f5e0b73354">
Current implementation
https://magna-react.vercel.app/components/drawer

**Comment by rwharrisjr** [comment]
Closing until magnetic tells us otherwise
