### ISSUE TITLE
Add ability to set props for each row in ADataTable

### ISSUE THREAD

**Issue by danlesko** [cisco-sbg-ui/magna-react#578]
**Is your feature request related to a problem? Please describe.**
Discovered I wanted this functionality when I created a hoverable tooltip for Associated Profiles in the Deployments table in XDR. The tooltip gets toggled when hovering the button that displays # of associated profiles in the deployments table. We are able to disable the tooltip when hovering the next button of profiles, but the tooltip doesn't go away when hovering subsequent rows which makes for an odd UX experience. 

**Describe the solution you'd like**
Ability to add an onMouseEnter / onMouseLeave event for rows in ADataTable. 

**Describe alternatives you've considered**
N/A

**Additional context**
https://github.com/advthreat/securex-ui-monorepo/pull/1501#pullrequestreview-1771474527

**Comment by androche** [comment]
Hey @danlesko  - I think what you are looking for might be solved by http://localhost:8001/components/triggertooltip#usage

**Comment by danlesko** [comment]
> Hey @danlesko - I think what you are looking for might be solved by http://localhost:8001/components/triggertooltip#usage

I will check it out, I was not aware of exactly how this component is used.

**Comment by danlesko** [comment]
Actually so this functionality seemingly works but I need the functionality for the implementation of AMenu that I have. @rwharrisjr and I chatted earlier and he said he didn't think this was too difficult of a thing to implement but also not urgent.

**Comment by androche** [comment]
Ah, I gotcha - not quite the traditional tooltip.
