### ISSUE TITLE
[BUG] Link Button variant styling is inconsistent

### ISSUE THREAD

**Issue by sabrinamokerji** [cisco-sbg-ui/magna-react#588]
**Describe the bug**

[Link Buttons](https://magna-react.vercel.app/components/button#link-buttons) are styled incorrectly. They should match the secondary and tertiary styling shown in the [button variants](https://magna-react.vercel.app/components/button#magnetized-left--re-skin-only-right) section. However, the text is the wrong color and the font-weight does not match.

**To Reproduce**

1. Go to [Button Variants](https://magna-react.vercel.app/components/button#magnetized-left--re-skin-only-right) 
2. Observe secondary and tertiary button styles
3. Go to [Link Buttons](https://magna-react.vercel.app/components/button#link-buttons) 
4. Observe that secondary and tertiary styles are different

**Expected behavior**
Link Button styling should match button variant styling.

**Screenshots**

<img width="1540" alt="Screenshot 2024-01-06 at 5 23 01 PM" src="https://github.com/cisco-sbg-ui/magna-react/assets/12389266/e4ba347b-a9ae-4596-9b7c-ebc7ba8c96f4">

<img width="815" alt="Screenshot 2024-01-06 at 5 22 53 PM" src="https://github.com/cisco-sbg-ui/magna-react/assets/12389266/bea239b6-77b2-46f8-a9bd-e631026cd38a">

**Additional context**
It also looks like we could remove the "re-skin" section under variants since the defaults should be magnetized now.

**Comment by androche** [comment]
@rwharrisjr FYI adding that this looks like this was somehow impacted by updates to our menu selects which removed the link styling per magnetic which has no style differences links in menus. When bringing back these styles we'll just want to make sure we keep them separated.  

https://magnetic.cisco.com/0a43ab5cd/p/321929-dropdown/b/8612ff
![Screenshot 2024-01-08 at 9 13 14 AM](https://github.com/cisco-sbg-ui/magna-react/assets/112431822/39916823-610d-4e05-ac26-d896e59825c6)

![Screenshot 2024-01-08 at 9 08 16 AM](https://github.com/cisco-sbg-ui/magna-react/assets/112431822/82e4a360-34a1-4202-bbfd-45631c5afe5e)
