### ISSUE TITLE
`onlyIfTruncated` prop of `ATriggerTooltip` does not work for vertically overflown content

### ISSUE THREAD

**Issue by vdineva** [cisco-sbg-ui/magna-react#597]
**Describe the bug**
The `ATriggerTooltip` with `onlyIfTruncated` prop should consider the case where a content is truncated vertically as well.
An HTML element may be overflown vertically, horizontally or both. [Reference](https://stackoverflow.com/questions/9333379/check-if-an-elements-content-is-overflowing/9541579#9541579)

**To Reproduce**
```
() => {
    const longText = "Some text that gets truncated, Some text that gets truncated, Some text that gets truncated, Some text that gets truncated,  Some text that gets truncated,  Some text that gets truncated,  Some text that gets truncated,  Some text that gets truncated";
    const noTruncation = "Text that does not get truncated";

return (

<>
  <ATriggerTooltip placement="top" content={longText} onlyIfTruncated>
    <div
      style={{
        display: "-webkit-box", 
        whiteSpace: "normal",
        "-webkitLineClamp": "2",
        "-webkitBoxOrient": "vertical",
        overflow: "hidden"
      }}>
      {longText}
    </div>
  </ATriggerTooltip>
  <br />
  <br />
  <br />
  <br />
  <ATriggerTooltip placement="top" content={noTruncation} onlyIfTruncated>
    <div>{noTruncation}</div>
  </ATriggerTooltip>
</>
); 
} 
```

In the above snippet of code the content is truncated because it goes above 2 lines (vertically overflown)

**Expected behavior**
Tooltip shows in example code above

**Comment by androche** [comment]
@vdineva  Would you mind showing a demo or some screenshots of what you are seeing for us to better understand?  That would be helpful -  I tried to load in the snippet and added setState to it, but I didn't see much of anything happening.
