### ISSUE TITLE
Add Ability For Horizontally Aligned Radio Buttons

### ISSUE THREAD

**Issue by danlesko** [cisco-sbg-ui/magna-react#616]
**Is your feature request related to a problem? Please describe.**
Default radio button behavior is to have the buttons vertically stack. It would be nice to have an easy way to tell the buttons to horizontally align.

**Describe the solution you'd like**
Add ARadioGroup wrapper for radio buttons that assist in defining the alignment, among other possible radio button enhancements. 

**Describe alternatives you've considered**
Just using `display:flex` in a div wrapping the radio buttons. 

**Additional context**
Example mockup: 
![Modal _ Secure Client](https://github.com/cisco-sbg-ui/magna-react/assets/11219427/c3f893c6-e8f3-4ec5-92c7-db0aef591eb1)

**Comment by rwharrisjr** [comment]
Good opportunity to add more of the magnetic spec as options too
