### ISSUE TITLE
Entire table header of `ADataTable` is used for sorting instead of just the text

### ISSUE THREAD

**Issue by sabrinamokerji** [cisco-sbg-ui/magna-react#66]
**Describe the bug**

The click action on the table headers for `ADataTable` span across the entire header instead of just the text. I noticed this when I clicked outside of a menu to close it and the table unexpectedly resorted.

This is especially unexpected when the table is full width and there is such a big space between the headers:

<img width="1890" alt="Screenshot 2022-12-13 at 6 40 50 PM" src="https://user-images.githubusercontent.com/12389266/207476447-95fc208f-c491-47a8-a870-f314037aa02c.png">

**To Reproduce**

1. Add a full page `ADataTable`
2. Make one column bigger than the rest
3. Click on the big empty space in the header between the big column and the next column
4. Observe the table sorting

**Expected behavior**

The table should only sort when the user clicks directly on the header column text. 

**Additional context**

Perhaps we can add something like Material UI does. They have the click handler on a `<span>` wrapping the text inside of the `<th>`:

https://mui.com/material-ui/react-table/#sorting-amp-selecting

**Comment by rwharrisjr** [comment]
Resolved by #33
