### ISSUE TITLE
Error Styling not working for Text Input and Textarea components 

### ISSUE THREAD

**Issue by meggettt** [cisco-sbg-ui/magna-react#664]
**Describe the bug**
When using the `hints` prop instead of the deprecated `hint`, the border of the text input does not change when a hint is passed in with the `validationStateOverride` set to `danger`.

**To Reproduce**
Pass an array containing a hint into the `hints` prop for TextArea or Text Input components. A description of the hint pops up, but the border color remains the same. 

**Expected behavior**
On an input error, the border of the input should match the corresponding Figma -
(https://www.figma.com/file/oVZWatImEIbl1c8sjdGxi0/branch/YNkCw8yeaOOOuvxWtyRz4X/%F0%9F%A7%B2--Magnetic-Design-Library?type=design&node-id=5193-37461&mode=design&t=GqbxgDXZgQ0S7nNR-0)

**Screenshots**
![image](https://github.com/cisco-sbg-ui/magna-react/assets/141422236/760fc8f4-bd12-4e0f-8a13-5aeec20a2bf8)

**Comment by rwharrisjr** [comment]
The hints validation state override is independent of the input validation state. Use `validationState="danger"` on `ATextInput` to get the desired border.
