### ISSUE TITLE
Add Magnetic breakpoints

### ISSUE THREAD

**Issue by sabrinamokerji** [cisco-sbg-ui/magna-react#671]
### **Is your feature request related to a problem? Please describe.**

Yes, we are using the Magnetic design system, which has different breakpoints than are what's in magna-react. There are a lot of discussions happening about design changes across XDR that are supposed to be using the Magnetic defined breakpoints, so we'll need those in this library.

Also, I could not find what the magna-react breakpoints were anywhere on the [docs site](https://magna-react.vercel.app/services/breakpoint). It would be helpful if all of the breakpoints were listed somewhere.

**Edit:** I found the breakpoint definitions listed on the [helper classes page](https://magna-react.vercel.app/components/app#helper-classes). It might be helpful to put it somewhere more prominent or at least link to this page from `useMediaQuery` and `useABreakpoint`.

Magna-react breakpoints are:

xs: 479px
sm: 767px
md: 992px
lg: 1200px
xl: 1440px

### **Describe the solution you'd like**

Add Magnetic breakpoints to magna-react. I know we can't rip the old ones out or change them for backward compatibility, so maybe the Magnetic breakpoints could be added in addition?

Also, is there a way to expose these variables for us to use in our app similar to color tokens?

[Magnetic breakpoints](https://magnetic.cisco.com/0a43ab5cd/p/077cd1-layout--page-templates/t/57e483)

<img width="872" alt="Screenshot 2024-03-29 at 1 35 46 PM" src="https://github.com/cisco-sbg-ui/magna-react/assets/12389266/9adb3cbe-d9bb-4c63-83db-127be678b69e">

**Comment by rwharrisjr** [comment]
Changing breakpoints will be a good candidate for the 2.0 release
