### ISSUE TITLE
ACopyButton: Consider extending the time the confirmation is shown to the user

### ISSUE THREAD

**Issue by vdineva** [cisco-sbg-ui/magna-react#693]
This is a request to extend the time for the confirmation message that's shown to the user after they hit the ACopyButton element.

It's currently shown for a very brief time, making it almost impossible to see what was shown.

https://github.com/cisco-sbg-ui/magna-react/assets/791418/e3228f15-8595-469c-b63b-3309bd3e7fde

**Comment by wlorand3** [comment]
**4/30 UI Dev Audit Update**
...curious, so took a quick look at the component - the setTimeout has a 300 on it, which is less than a second; perhaps this is a typo/bug with the intention of 3000 or 3 seconds which seems more reasonable to me on first glance, though there may be an established magna-react pattern for this;
Not sure this really calls for a prop to customize the time for a copy action, but would agree that under 1 second is a bit too brief

**Comment by vdineva** [comment]
I think 3 seconds would be good, here's an example from GitHub:


https://github.com/cisco-sbg-ui/magna-react/assets/791418/2f744702-cd7e-4272-aaa0-39d7f6e5a6ab

**Comment by rwharrisjr** [comment]
I reworked the implementation to not be based on a timer (and the timer wasn't actually the time the tooltip showed, it was a hack). The Copied tooltip should now disappear when the mouse is moved out of the button element, which is expect for normal tooltips.

The tooltip will remain open while the mouse is on the button.
