### ISSUE TITLE
Accordion has extra space underneath when collapsed.

### ISSUE THREAD

**Issue by guptar8jan** [cisco-sbg-ui/magna-react#709]
**Describe the bug**
<img width="896" alt="image" src="https://github.com/cisco-sbg-ui/magna-react/assets/10874564/e16e12ef-2f12-42ed-96f2-9749c8cb8af6">

Style issue: Accordion body is set to `display:block`
<img width="292" alt="image" src="https://github.com/cisco-sbg-ui/magna-react/assets/10874564/217d6873-2c81-4510-b77b-17cf4a6ecc43">

**To Reproduce**
1. Go to control center (https://xdr.int.iroh.site/control-center)
2. Click on Customize button.
3. Scroll down to through all the tiles.
4. See issue where space is at the bottom.

**Expected behavior**
No extra space.

**Environment (please complete the following information):**
 - Device: [e.g. Desktop, iPhone6]
 - OS: [e.g. iOS, Ubuntu]
 - Browser [e.g. Chrome, Safari]

**Additional context**

**Comment by androche** [comment]
Resolved in #710
