### ISSUE TITLE
Tertiary and tertiary alt button should have 0 padding

### ISSUE THREAD

**Issue by bredy** [cisco-sbg-ui/magna-react#714]
**Describe the bug**

There's a consistency issue with our tertiary and tertiary alt button's padding. While it shares the same padding as other buttons, it lacks a border. This creates a visual mismatch that doesn't align with its usage within text content.  Additionally, the current padding is frequently overridden, especially in text, causing further inconsistency.

Was trying to verity this issue in "Magnetic UX Support" room:

![Screenshot 2024-05-09 at 12 55 53](https://github.com/cisco-sbg-ui/magna-react/assets/178547/b98d6d5b-0a0f-44f1-859d-5a613bd8f6d4)

Figma Magnetic is also quite clear zero padding (except button groups): https://www.figma.com/file/oVZWatImEIbl1c8sjdGxi0/🧲--Magnetic-Design-Library?type=design&node-id=207-0&mode=design&t=STeERGnU5BBDzScW-0

**Expected behaviour**

From Magnetic team response - tertiary and tertiary alt should have:
- 0px padding all around,
- 4px spacing between icon(s) and text label

**Proposed solution**

Because we would like to keep magna-react interface backward compatible I suggest to add to `AButton` new properties `tertiaryPaddingLess` and `tertiaryAltPaddingLess` (or other with similar meaning) which removed the padding while keeping other properties unchanged.

**Comment by androche** [comment]
Hi @bredy - this has been brought up a lot since we changed to magnetic design - a lot of feedback has been given to the magnetic team on how this style is very odd looking and not helpful when it comes to accessibility.  Last year Jesse shared they are considering updates to this design so magna decided to hold off, but that was last year.  It might be worth us checking back in with them to see where they landed on these decisions.

**Comment by bredy** [comment]
Thanks for the explanation @androche ! I've taken this on because we've been running into this issue a few times lately as I wrote above. It seems like UX designers are using this element as one with no padding (now ?). You can see the magnetic team's explanation above in the screenshot, which confirms they're treating it as a no-padding element. However, it might be worth double-checking to be sure.

**Comment by androche** [comment]
Yea it's always been no padding since switching to magnetic, but we were told (last year) that might be reconsidered.  I will definitely follow back up on the status as it seems like we should just update it at this point!

**Comment by androche** [comment]
@bredy followed up and no further discussion on the matter, but it was suggested that I should inquire further with magnetic UX.  I'd rather not be the spokesperson for the padding community and will instead let the customers feedback ring in 😄 We'll line this up for magna 2.0!
