### ISSUE TITLE
Improve Magnetic breakpoint transition

### ISSUE THREAD

**Issue by sabrinamokerji** [cisco-sbg-ui/magna-react#726]
## Related issue and PR
https://github.com/cisco-sbg-ui/magna-react/issues/671
https://github.com/cisco-sbg-ui/magna-react/pull/716/files#r1597189885

## Description

I had requested that we add Magnetic breakpoints to magna in [this issue](https://github.com/cisco-sbg-ui/magna-react/issues/671). However, it seems that the breaking change will have a large impact since the new breakpoints are so vastly different than the previous. 

https://github.com/cisco-sbg-ui/magna-react/commit/9fb7280cbd508563eeb485e25b004424434ed51f#diff-ee1bec339fa21d8d0fc83897581a21da528133cefb96d998e62b23c77eb4662fL514-R518

<img width="330" alt="Screenshot 2024-05-17 at 5 26 08 PM" src="https://github.com/cisco-sbg-ui/magna-react/assets/12389266/030d35a9-42fa-4614-9fb2-bd9b7294cab5">

<hr>

I propose that we adjust these breakpoints slightly to keep the breakpoint sizes closer to the number range that they were before:

xs: 479
sm: 767
md: 960
lg: 1280
xl: 1680
xxl: 2080

**Comment by androche** [comment]
@sabrinamokerji I pulled in updated magna into incident manager (on shell app) just to click around and check it out and tbh I can't really detect a difference.  Maybe it's that incident manager would be ok and other apps not? Wondering if it might actually not be too bad.
