### ISSUE TITLE
Table sorting is not working correctly

### ISSUE THREAD

**Issue by sabrinamokerji** [cisco-sbg-ui/magna-react#74]
**Describe the bug**

1. The first time the user clicks on the sortable header that is active on load, it does nothing. It does not sort.
2. The sort icon disappears after the first click.
3. The sort icon reappears after clicking again, but then disappears again every 3rd click.
4. The sort icons are supposed to be visible for every sortable header on load in an inactive state, but only one header shows a sort icon at a time.
5. The header text next to the sort icon jumps up and down as it is not aligned with the rest of the table headers when it has an icon next to it.
6. Sort icon is too small. Magnetic shows it larger.
7. The sort header text is user selectable.

**Expected behavior**

1. The sort header should sort the table the first time it is clicked if it's the active header already being used for sorting. 
2. The sort icon should never disappear.
3. The sort icon should change to a disabled state (arrow icons with no arrow colored in) when a different header is clicked.
4. The sort icons should always be visible. The user will have no way of knowing which columns are sortable if only 1 shows at a time. If a header is not currently being used sorting, it should show the disabled arrow icon as mentioned at the bottom of this issue - https://github.com/cisco-sbg-ui/magna-react/issues/33
5. The header text should always be in line with the other table headers, regardless if an icon is next to it or not.
6. Sort icon should match the size that Magnetic uses.
7. The sort header text is not user selectable.

**Screenshots**

Left side is Magnetic, right side is magna-react. Notice the difference in icon size. Also notice that the header with the icon is not aligned with the header without one:

<img width="426" alt="Screenshot 2023-01-05 at 4 51 23 PM" src="https://user-images.githubusercontent.com/12389266/210895561-32742ffb-5d42-43d8-82db-0518eb56b921.png">

**Recording showing behavior:**

[Screen Recording 2023-01-04 at 7.40.58 PM.mov.zip](https://github.com/cisco-sbg-ui/magna-react/files/10348741/Screen.Recording.2023-01-04.at.7.40.58.PM.mov.zip)

**Additional context**

Behavior of "disabled" icons being used for non-active sort columns is explained at the bottom of this issue - https://github.com/cisco-sbg-ui/magna-react/issues/33

**Comment by rwharrisjr** [comment]
@sabrinamokerji for #4, none of the three designs I've been given indicate a sort icon should always be visible. Working example in harbor (which granted does not match the figma, and zeroheight doesn't have content for tables) http://harbor.cisco.com/?path=/docs/core-data-table-table--features. Which magnetic specification are you seeing that in?

1) working on demo site
2) does not appear to match design specs
3) see 2
4) see 2
5) resolved in https://github.com/cisco-sbg-ui/magna-react/pull/89
6) resolved in https://github.com/cisco-sbg-ui/magna-react/pull/89
7) does not match design spec (harbor)

**Comment by sabrinamokerji** [comment]
Hi @rwharrisjr, the sort icons being visible can be seen in the Magnetic component Figma: https://www.figma.com/file/oVZWatImEIbl1c8sjdGxi0/branch/yU3qYkj6T2kfN4XYtUkEeD/%F0%9F%A7%B2--Magnetic-Design-Library?node-id=5259%3A38404&t=BNqdfbtypwJCGHFm-0

You can see in this mockup that it shows 2 header sort icons at the same time. They don't have any mock up showing that appears after clicking.

The only difference we are asking for is the ability to have the option for a sort icon look "inactive" (no arrows filled) because our API does not let the user sort on multiple fields at the same time, it only allows 1 at a time. The mockup looks like it assumes the API can sort on multiple fields at a time: 

<img width="917" alt="Screenshot 2023-01-10 at 1 05 39 PM" src="https://user-images.githubusercontent.com/12389266/211639469-188e6286-22b7-4cc8-beb9-11834be822e1.png">

Since Magnetic did not account for the use case where only one can be sorted on at a time, our designer provided the idea of having icons show "inactive" if they aren't actively being sorted on:

![image](https://user-images.githubusercontent.com/12389266/211651212-ce832ffe-0e0f-4961-a047-40b6bc829f43.png)

I'll send a message in the Magnetic Design System Support channel to get confirmation on this behavior

**Comment by rwharrisjr** [comment]
@sabrinamokerji I think everything we can resolve for this is now in the latest beta build (1.0.0-beta.7). If y'all notice anything still off we can track it in a new issue.
