### ISSUE TITLE
Add markdown editor actions Phosphor icons 

### ISSUE THREAD

**Issue by derrick-snider** [cisco-sbg-ui/magna-react#77]
### Description
UI should present a consistent set of icons across SecrueX. These "markdown" icons will be utilized in the Worklog section of SecureX Incident response flow, on note taking modals, and editing modals/pages.
**Use lightweight outline versions.** This supports issues https://github.com/advthreat/incident-manager/issues/68 and https://github.com/advthreat/incident-manager/issues/88 and worklog tab https://github.com/advthreat/incident-manager/issues/144 

### Context
Incidents > Worklog > add note
Incidents > Description edit modals
Incidents > Note taking modals
Intelligence

### Checklist
- [ ] Use lightweight outline versions
- [ ] replace existing atomic icons
- [ ] add `text-h` Header icon
- [ ] add ` text-bolder` bold icon
- [ ] add `text-italic` italic icon
- [ ] add `text-strikethrough` strikethrough icon
- [ ] add `link-simple` link icon
- [ ] add `quotes` quotes icon
- [ ] add `code` code icon
- [ ] add `list-bullet` bullet list icon
- [ ] add `list-numbers` number list icon
- [ ] add `list-checks` checklist icon

### Images
<img width="626" alt="image" src="https://user-images.githubusercontent.com/429803/210853371-f18baa3d-750e-4447-822e-0a2a7f2cdb99.png">

pulled names from these (example):
<img width="976" alt="image" src="https://user-images.githubusercontent.com/429803/210855719-01bd01c8-cd72-4296-8725-a8084bab901e.png">

### Links
https://github.com/phosphor-icons/phosphor-home

### CC
@DarMontou

**Comment by brennarvo** [comment]
Given the way icons are currently rendered within Magna React, we need to use the fill weight from Phosphor to ensure we support both light/dark mode versions of the icon.

All of the icons look nearly the same in the fill weight, with the exception of the quotes icon:
<img width="324" alt="Screenshot 2023-01-05 at 4 00 50 PM" src="https://user-images.githubusercontent.com/94568316/210888385-c5dd0a90-e3c2-431d-9465-8d179ccb7c63.png">

The branch deployment for this can be found here so you can look at the other icons I added: https://magna-react-lr2iy81hz.securex-preview.app/components/icon#magna-icon-gallery

**Comment by sabrinamokerji** [comment]
Would it be more performant to just use the Phosphor Icon React component library in magna?
https://github.com/phosphor-icons/phosphor-react

**Comment by rwharrisjr** [comment]
@sabrinamokerji No, including the library directly to be bundled would require a 4mb addition as a dependency. By design magna-react has no dependencies. Adding the phosphor-react library as a peer dependency is outside the scope of this project.
