### ISSUE TITLE
Double border for text input in magna-react v2.0.3

### ISSUE THREAD

**Issue by vdineva** [cisco-sbg-ui/magna-react#774]
v2.0.3
![Screenshot 2024-07-08 at 11 26 30](https://github.com/cisco-sbg-ui/magna-react/assets/791418/187f375a-f878-44e0-8c09-997c92c64ca5)

v1.1.0-beta.22
![Screenshot 2024-07-08 at 11 26 41](https://github.com/cisco-sbg-ui/magna-react/assets/791418/78d936b2-2621-4c4b-bd51-64493f356694)

**Comment by rwharrisjr** [comment]
<img width="265" alt="Screenshot 2024-07-08 at 10 30 05 AM" src="https://github.com/cisco-sbg-ui/magna-react/assets/23561587/9f3bc992-d8bf-4985-976f-8378addac603">

This was changed do align with the current magnetic design
