### ISSUE TITLE
`ACol` responsive breakpoints (e.g. `sm`, `md`, etc.) do not work

### ISSUE THREAD

**Issue by brennarvo** [cisco-sbg-ui/magna-react#778]
**Describe the bug**

Breakpoints have stopped working with `ACol`. For example:

```jsx
<ACol sm="12" md="8" lg="6" />
```

**To Reproduce**

1. Go to any playground editor on the docs site
2. Paste the following code into the editor:
    ```jsx
    <AContainer>
      <ARow className="mb-4">
        <ACol
          style={{ background: "var(--brand-bg-default)", color: "white" }}
          sm="12"
          md="6"
          lg="4"
          className="cisco-blue text-center"
        >
          1 column
        </ACol>
      </ARow>
    </AContainer>
    ```
3. Adjust the width of your browser
4. Observe that the size of the column does not change

**Expected behavior**

The width of the column should adjust. For an example of how this used to work, you can paste the code snippet above [into an older preview branch of Magna React before version 2](https://magna-react-2yqwh5869.securex-preview.app/components/layout).

**Screenshots**

**Environment (please complete the following information):**
 - Device: Desktop
 - OS: macOS
 - Browser: Chrome
 - Version 122.0.6261.94

**Comment by androche** [comment]
@rwharrisjr bumping this one as we have another report of it:

```
<AContainer>
  <ARow className="mb-4">
    <ACol className="dark-cool-grey white--text text-center" sm="12">
      First column
    </ACol>
    <ACol className="dark-cool-grey white--text text-center" sm="12">
      Second column
    </ACol>
    <ACol className="dark-cool-grey white--text text-center" sm="12">
      Third column
    </ACol>
  </ARow>
</AContainer> 
```

**Comment by rwharrisjr** [comment]
The breakpoints do actually work, but since we added more they need to be adjusted product side to hit the intended points with the new values

**Comment by androche** [comment]
@rwharrisjr Are you sure? I have these set to the smallest screen on medium/lg doesnt matter, these should fall into a full width horizontal col.

So it should go from here: First Column -> Second Column -> Third Column
to:
First Column
Second Column
Third Column

![Screenshot 2024-08-23 at 11 40 34 AM](https://github.com/user-attachments/assets/368a13b8-8f98-4cb9-8280-255eaad0b2b6)
