### ISSUE TITLE
[BUG]: Issues with AMultiSelect

### ISSUE THREAD

**Issue by guptar8jan** [cisco-sbg-ui/magna-react#779]
**Describe the bug**
Context: Issues observed during development of JIRA Q4 Epic
[XDR Notifications- Enable users to send notifications to instant messaging systems.](https://cisco-sbg.atlassian.net/browse/XDR-1561)

1.No placeholder is showing up, so user don't know where to type.
<img width="320" alt="image" src="https://github.com/user-attachments/assets/a7d15912-d119-4e70-ac2e-cd1a0c2b2541">

2. Label is not greyed out when component is disabled.
<img width="396" alt="image" src="https://github.com/user-attachments/assets/efeec294-49f2-4ba3-af12-9a0347ebfe67">

3. Seeing some UI Overlapping after adding initial search hit (screenshot)
<img width="395" alt="Screenshot 2024-07-12 at 12 27 52 PM" src="https://github.com/user-attachments/assets/794b1910-5e9e-4df0-b8c0-87535466c910">

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Device: [e.g. Desktop, iPhone6]
 - OS: [e.g. iOS, Ubuntu]
 - Browser [e.g. Chrome, Safari]

**Additional context**

**Comment by wlorand3** [comment]
**7/15 UI Dev Audit Update:**
Added screenshot of overlapping UI - temp assigning to Robert just for visibility / delegation;
The latest UI uses Numbers in Tags for Search Result hits rather than full search results in tags so screenshots here are recent but already out of date - Added context re: XDR feature development

**Comment by rwharrisjr** [comment]
For 1) magnetic doesn't have a placeholder in the design for selects with tags

<img width="393" alt="Screenshot 2024-07-15 at 3 02 51 PM" src="https://github.com/user-attachments/assets/539b0be9-bf23-46f8-91b4-20a2d74aed84">


For 2) Form labels don't get grayed out when the control is disabled, except for checkboxes (in which the label is part of the control itself)

<img width="386" alt="Screenshot 2024-07-15 at 3 02 37 PM" src="https://github.com/user-attachments/assets/1b93518c-103b-4d44-8509-21b99bc1e208">
