### ISSUE TITLE
Add support for `sass` v1.77.8

### ISSUE THREAD

**Issue by vdineva** [cisco-sbg-ui/magna-react#781]
We'd like to upgrade to the latest version of `sass` - v1.77.8 but we're getting a lot of warning coming from the magna-react package:

![Dashboard Page -- Labels and values -- should assign label to devices (failed)](https://github.com/user-attachments/assets/542053bc-d1c9-4a7c-8d5e-45bad2f53417)

**Comment by androche** [comment]
@vdineva this appears to be an issue with the latest sass release - After some research, can you try
`npm i sass@1.77.6 --save-exact` in your project as this has worked for some.  I also ran the sass 1.77.8 upgrade locally and didn't get any warnings, but we'll continue to help debug if your team doesn't find solutions!

Similar issue as of 3 days ago: https://github.com/twbs/bootstrap/issues/40621

**Comment by rwharrisjr** [comment]
Seems like we should be able to move the `@include` statements below the last css property in a group and resolve the issue in magna.

**Comment by rwharrisjr** [comment]
https://github.com/cisco-sbg-ui/magna-react/pull/782 resolves the warnings in my dev env

**Comment by androche** [comment]
![Screenshot 2024-08-20 at 4 19 35 PM](https://github.com/user-attachments/assets/66f7c5a6-8ec7-4205-9045-67efae44567d)
More warnings were found ^

**Comment by androche** [comment]
Fixed in: https://github.com/cisco-sbg-ui/magna-react/pull/843
