### ISSUE TITLE
ALoader issue - variant progressbar

### ISSUE THREAD

**Issue by guptar8jan** [cisco-sbg-ui/magna-react#789]
**Describe the bug**

ALoader issue - variant progressbar: only works with label.
WORKS:
<ALoader variant="progressbar" size="medium" indicatorProps={{indeterminate: true}}>Medium progress bar</ALoader><br />
 NO SHOW:
<ALoader variant="progressbar" size="medium" indicatorProps={{indeterminate: true}}></ALoader><br />
      
**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Device: [e.g. Desktop, iPhone6]
 - OS: [e.g. iOS, Ubuntu]
 - Browser [e.g. Chrome, Safari]

**Additional context**

**Comment by androche** [comment]
I went to create the new component and it said it was already made!
https://magna-react.vercel.app/components/progressbar
Looks like we have another component for this.  @guptar8jan could you try with this one in the meantime to see if it fixes the issues and we will continue work adding the variants and such.

**Comment by androche** [comment]
Added in: https://github.com/cisco-sbg-ui/magna-react/pull/839
