### ISSUE TITLE
ALoader issue within a AButton

### ISSUE THREAD

**Issue by guptar8jan** [cisco-sbg-ui/magna-react#790]
**Describe the bug**

ALoader within a AButton is not aligned center.
CODE
```
<AButton onClick={() => reloadDevices()} secondary>
              <ALoader variant="spinner" size="small" />
        </AButton>
 ```

<img width="69" alt="image" src="https://github.com/user-attachments/assets/dde40837-fb1d-4d8f-a645-6a92da1da341">

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Device: [e.g. Desktop, iPhone6]
 - OS: [e.g. iOS, Ubuntu]
 - Browser [e.g. Chrome, Safari]

**Additional context**

**Comment by rwharrisjr** [comment]
@guptar8jan 

To pick up magnetic styles automatically use `loading` as a prop on `AButton`, rather than putting the loader in directly. Bit simpler code wise

https://github.com/cisco-sbg-ui/magna-react/pull/783 was just merged to address a margin issue when there is no button label
