### ISSUE TITLE
Issues with AMultiselect

### ISSUE THREAD

**Issue by guptar8jan** [cisco-sbg-ui/magna-react#794]
**Describe the bug**

1. "required" only works if value prop is set to null. It should work with empty array.
2. "Required" validation do not reset when AMultiselect is disabled. Running `formref.current.reset()` does not help.
3. when modal is scrolling AMultiselect -> dropdown scrolls as well.
<img width="384" alt="image" src="https://github.com/user-attachments/assets/a7e5470c-01ff-4135-9191-806b4cdf7e93">

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Device: [e.g. Desktop, iPhone6]
 - OS: [e.g. iOS, Ubuntu]
 - Browser [e.g. Chrome, Safari]

**Additional context**

**Comment by rwharrisjr** [comment]
https://github.com/cisco-sbg-ui/magna-react/pull/795 addresses items 1 and 2. I *think* 3 may be addressed by other changes for tracking the menu positioning better, but we may need to add additional scroll checking. This will be easier to test after #792
