### ISSUE TITLE
ADataTable and sorting behavior

### ISSUE THREAD

**Issue by vdineva** [cisco-sbg-ui/magna-react#796]
The `ADataTable` component supports sorting by a given column in ascending, descending and undetermined order. I think once the table it sorted, we should not set it to unsorted/undetermined sort and once sorted, the table should be either in sorted asc or sorted desc state.

See ofr reference Magnetic's team response to my question: webexteams://im?space=57814fd0-d3e4-11ed-a975-972df1e25c08&message=3b815120-4857-11ef-9580-cdcba3c2c9d0

https://github.com/user-attachments/assets/98102fd3-6051-4438-916f-d2c5c46ec11a

**Comment by rwharrisjr** [comment]
@vdineva  `disableSortReset` will disable the unsorted state (once sorted), and I think aligns with what you suggested. I didn't see anything in the magnetic guidelines except that unsorted is an option, but not what to do when toggling sort.

**Comment by vdineva** [comment]
@rwharrisjr please see the question I asked here: webexteams://im?space=57814fd0-d3e4-11ed-a975-972df1e25c08&message=3b815120-4857-11ef-9580-cdcba3c2c9d0

**Comment by androche** [comment]
@vdineva I do remember a conversation a long time ago about the sort logic.  I think it should be back up a larger discussion as CDS has the 3 sort order as well.  https://magnetic-storybook-prod.aiadsbg-a-1.prod.infra.webex.com/storybook/index.html?path=/story/components-table--playground

I think we'd still want to be on the same page though - There is a process for requesting a change in CDS, but I think they would be able to start that process faster.  I can respond to the chat ticket with more information to help prompt.

**Comment by androche** [comment]
@vdineva Received clarification from Patricia:  "I was testing this in Storybook using the # column, where the baseline order is the same as the ascending order, so it only has two filter states. Just checked again and we do have a 3 sort order."   Good to have an answer though because it has been brought up in the past. We will go ahead and close for now.
