### ISSUE TITLE
Add truncation to table headers and cells

### ISSUE THREAD

**Issue by sabrinamokerji** [cisco-sbg-ui/magna-react#81]
**Is your feature request related to a problem? Please describe.**

Yes - when table columns become too small to fit the horizontal content, the column text gets cut off.

**Describe the solution you'd like**

Truncation to automatically be added to table headers and cells.

**Describe alternatives you've considered**

We've tried adding our own truncation to every table's headers and cells, but it's causing issues when the `th` has a sort icon next to it. `ADataTable` should provide truncation out of the box so everyone who uses it doesn't have to remember to add this to every table.

Our attempt at trying to add this to all tables ourselves. Notice the issue with the `th` with the sort icon:

<img width="731" alt="Screenshot 2023-01-05 at 4 59 30 PM" src="https://user-images.githubusercontent.com/12389266/210896483-884a349a-f344-4c85-b407-d56f8a92640a.png">

How the table looks with none of our custom truncation:

<img width="1471" alt="Screenshot 2023-01-05 at 5 05 07 PM" src="https://user-images.githubusercontent.com/12389266/210897026-89e97796-c2f6-4a95-9d7a-c3a50bb2b4dc.png">

**Comment by rwharrisjr** [comment]
The header content can be reworked to account for the sort icon, but I think cell behavior should be up to the consumer. It also seems like the usage/ux design of the table should be changed if short headers and content are often getting truncated.

**Comment by sabrinamokerji** [comment]
@rwharrisjr yes probably, but unfortunately every table we get from design includes text that gets truncated 😅  I see where you're coming from about consumers needing control of the cell truncation. Can it just be added for the `th` elements then?

**Comment by rwharrisjr** [comment]
@sabrinamokerji The `th` elements should be doable, we'll work on that.

**Comment by rwharrisjr** [comment]
@sabrinamokerji The best I can get this working right now is by having to manually set a header width in style for columns that should be truncated. Given the nature of `<table>` there is not a good way to make column widths act consistently and as expected for a responsive layout. 


![Screenshot 2023-01-09 at 12 51 37 PM](https://user-images.githubusercontent.com/23561587/211385223-b0fba13e-f2da-45ac-9f59-df8c2da41fb8.png)

Most discussions I've found recommend scrolling a table to avoid header cells needing to be truncated and getting ellipses (I get that that's not the design, but is seemingly the more common approach).

The PR associated with this issue does add the ability to pass a `style` prop to the header object to help for custom styling.
