### ISSUE TITLE
Need to revert scroll code

### ISSUE THREAD

**Issue by androche** [cisco-sbg-ui/magna-react#834]
Need to pick out scroll code from here https://github.com/cisco-sbg-ui/magna-react/pull/805 as it is causing menus to move with page scroll.  

![Screenshot 2024-08-14 at 2 48 39 PM](https://github.com/user-attachments/assets/b37d08f7-748f-4614-bddf-c9646ec8a54f)

**Comment by rwharrisjr** [comment]
This has been done
