### ISSUE TITLE
AMultiselect issue: if using component instead of text for option label; searching breaks

### ISSUE THREAD

**Issue by guptar8jan** [cisco-sbg-ui/magna-react#881]
**Describe the bug**

if using component instead of text for option label; searching breaks.
**
example option; using component for option label:
```
{
      name: "US",
      label: (
        <div>
          United States
          <span style={{color: "grey"}}>(10)</span>
        </div>
      )
    }
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Device: [e.g. Desktop, iPhone6]
 - OS: [e.g. iOS, Ubuntu]
 - Browser [e.g. Chrome, Safari]

**Additional context**

**Comment by androche** [comment]
Closing as this appears to be fixed:
```
    const label = {
      name: "US",
      label: (
        <div>
          United States
          <span style={{color: "grey"}}>(10)</span>
        </div>
      )
    }  
    
      <AMultiSelect
        {...label}
        items={items}
        itemValue="id"
        itemText="name"
        placeholder="Pick a Food Group"
        onSelected={(newValue) => {
          setValue1(newValue);
        }}
        value={value1}
      />
  ```    
      
      
![Screenshot 2024-10-18 at 4 26 01 PM](https://github.com/user-attachments/assets/0231825a-7c65-4cee-a72a-77b0dc78cc01)
