### ISSUE TITLE
2.5.0 dropdown issues

### ISSUE THREAD

**Issue by androche** [cisco-sbg-ui/magna-react#898]
Tests are failing in devices. Notes below:

**Issue 1:**
Floating UI uses a portal to render the dropdown & that is causing the elements to get hidden from the queries we use to assert stuff in our unit tests

In the DOM theres a aria-hidden attribute applied to a couple spans in the dropdown DOM tree but nothing that wraps the actual elements though

**Issue 2:**
This is a `<Select />` with a list of `<AItems />`. The checkboxes are not selectable 
![Screenshot 2024-09-25 at 12 52 49 PM](https://github.com/user-attachments/assets/a0aac041-a9ea-43fd-8755-37f19c9dfed1)

**Comment by androche** [comment]
More notes from Raj:

I think I found what's causing us issues in our unit tests - the visibility hidden style is getting applied on the listbox

https://github.com/cisco-sbg-ui/magna-react/commit/21b2dfe76682ab29d9d2cc59d922c62491ef4a48#diff-e545ce2b41c0977efb7ae4adc801136c5285c55a77a35d41bb8e52295a9e7cc9R232

**Comment by rwharrisjr** [comment]
That is a desired behavior - hiding the menu when the anchor is out of view. But I can see how that might cause problems in test cases. 

It might be easiest to disable that for now, and add that as a breaking change in the future.

Alternately we could refactor that to apply a class that sets visibility to hidden, and have the tests override that class for the sake of testing. Which seems like a bit much.

**Comment by androche** [comment]
Resoled in v2.5.3
