### ISSUE TITLE
AMultiSelect hover state

### ISSUE THREAD

**Issue by vdineva** [cisco-sbg-ui/magna-react#906]
When a user hovers over a AMultiSelect component the cursor is currently the default. It should probably be pointer, similarly to the ASelect component

**Comment by rwharrisjr** [comment]
This is by design. Since `AMultiSelect` is searchable, the cursor indicates the field can accept typed input. `ASelect` does not accept text input for filtering, so it shows the pointer cursor. This matches design and other implementations.
