### ISSUE TITLE
`AAlert` components with the `info` variant do not receive focus styling for the close button

### ISSUE THREAD

**Issue by brennarvo** [cisco-sbg-ui/magna-react#910]
**Describe the bug**

When tabbing through a page with an `AAlert` component with the `info` variant, the close ("x") button does not receive a focus style.

**To Reproduce**

1. [Navigate to the `AAlert` docs page](https://magna-react.vercel.app/components/alert)
2. Click inside the `success` alert that is rendered by default on the page
3. Press your <kbd>Tab</kbd> key
4. Observe that the "x" button receives a focus style
5. Change the `variant` in the same playground editor to `info`
6. Click inside the alert
7. Press your <kbd>Tab</kbd> key
8. Observe that the "x" button does *not* receive a focus style

**Expected behavior**

The `info` alert should receive a focus style like the other variants.

**Environment (please complete the following information):**
 - Device: Desktop
 - OS: macOS
 - Browser: Chrome
 - Version: 128.0.6613.138

**Comment by androche** [comment]
@rwharrisjr, looks like we have some subtle custom colors for these probably carried over from atomic.  Thinking we should probably remove those and go with the magnetic focus state?

**Comment by rwharrisjr** [comment]
Yep, need to align with magnetic
