### ISSUE TITLE
Add SharpSans Bold for H

### ISSUE THREAD

**Issue by derrick-snider** [cisco-sbg-ui/magna-react#92]
Magnetic uses SharpSans Bold for Heading/Primary title (H1 I think) it should be added so ui dev can use it.

### Checklist
- [ ] yes SBG has a license for SharpSans Bold, pull from link below

### Images
![image](https://user-images.githubusercontent.com/429803/212190521-2e518cf4-35bf-4ca5-980a-c5f35a3026b8.png)
![image](https://user-images.githubusercontent.com/429803/212190551-673d4717-b39b-4482-adea-ee4d9edf0421.png)

### Links
https://magnetic.cisco.com/0a43ab5cd/p/4119aa-typography/t/50c42f

**Comment by rwharrisjr** [comment]
@derrick-snider To use it automatically within magna-react we'd need to host the font files on the CDN. Without reading the license, I don't want to open up legal risk by hosting a licensed file set on a publicly accessible domain. 

The magnetic docs say that Inter is a valid fallback if the first font cannot be loaded or fails to load. We currently do host and use Inter within magna-react.

**Comment by derrick-snider** [comment]
Is `Inter` on the cdn?

**Comment by rwharrisjr** [comment]
@derrick-snider yes, https://github.com/advthreat/brand-assets/tree/master/public/fonts/inter
