### ISSUE TITLE
Add Alex Gonzalez to magna-react github

### ISSUE THREAD

**Issue by derrick-snider** [cisco-sbg-ui/magna-react#96]
This task is to provide required access to project: magna-react. 

Alex Gonzalez github: AlexGoDe
alexgo@cisco.com

add to https://github.com/cisco-sbg-ui/[magna-react](https://github.com/cisco-sbg-ui/magna-react)

**Comment by rwharrisjr** [comment]
Added to the `UX Team` for the `@cisco-sbg-ui` GitHub org
